### ISSUE TITLE
./dwg.spec:12342:5: error: format specifies type 'unsigned short' but the argument has type 'BITCODE_BL' (aka 'unsigned int') [-Werror,-Wformat]

### ISSUE THREAD

**Issue by billydotzhang** [LibreDWG/libredwg#1001]
System: macOS Monterey
Chip: Apple M2

I followed the README instructions.

When running `sudo make` or`sudo make install`, this error occurs.

The following image shows the error I encountered during execution.

![image](https://github.com/user-attachments/assets/a01f0842-6302-4cfd-a1ab-d8267f56bcc3)

**Comment by rurban** [comment]
Very good catch, clang! Thanks

**Comment by billydotzhang** [comment]
I try agin. Another bug kept me from going.

Is it necessary to `make`

I just need to implement the `dwg2dxf` functionality

How do I run it

![image](https://github.com/user-attachments/assets/b5970cf4-2236-465c-9954-cd6493b98cd5)

**Comment by billydotzhang** [comment]
@rurban  Excuse me, give me a hand~ Thanks~

**Comment by rurban** [comment]
To error on `VALUE_RS(0, 360)` is a bit too strict for my taste, but ok. I'll fix that also.

**Comment by billydotzhang** [comment]
@rurban   Good morning. I am back.  XD
![image](https://github.com/user-attachments/assets/80050a01-027e-433c-8bc6-0b60e29ad48a)

**Comment by rurban** [comment]
Billy.zhang ***@***.***> schrieb am Mo., 19. Aug. 2024, 06:36:

> @rurban <https://github.com/rurban> Good morning. I am back. XD
> image.png (view on web)
> <https://github.com/user-attachments/assets/80050a01-027e-433c-8bc6-0b60e29ad48a>
>

Now that's silly. What if you change the 0 to 0U?

**Comment by billydotzhang** [comment]
XD，I annotated it.

but.... 
![image](https://github.com/user-attachments/assets/5e923e2a-07d4-4e86-a862-dc74f81a5f05)
