### ISSUE TITLE
Invalid-allocation-size in function `add_ent_preview()`

### ISSUE THREAD

**Issue by skorpion98** [LibreDWG/libredwg#1006]
### Describe the bug
In file [in_dxf.c](https://github.com/LibreDWG/libredwg/blob/master/src/in_dxf.c#L6939), function `add_ent_preview()` invokes the `calloc()` function with an invalid value when a specific input is provided (`0x7fffffffffffffff` with the attached input).

### To Reproduce
Due to size constraints of this report, the archive we used to perform our tests is available at this [link](https://drive.google.com/file/d/1b7JYRr9pmlQ_IYF7jAG5tkwlMYVxHwxV/view?usp=drive_link), and it contains:
- the executable on which we performed our tests
- the input file that caused the bug
- the output of ASan confirming our finding

To reproduce the errors, simply run the given binary on the provided testcase files with a command like `./llvmfuzz /path_to_testcases/input`

The program has been tested on the OSS-Fuzz Docker image for this project using Ubuntu 20.04.During the compilation,we compiled using Address Sanitizer using the flag `--sanitizer=address`.

The hash commit used to perform the tests is `27118c4`.

**Environment**
- OS: Linux
- Version/Distribution: Ubuntu 20.04
- Architecture: x86_64

**Comment by rurban** [comment]
Harmless. If the calloc fails due to an overlarge user-input value, it fails with an Out of memory error.
But I fail now earlier when the size is > INTMAX_MAX
