### ISSUE TITLE
write line object to dwg file,then open file with autoCAD 2007, "The recover command may be able to restore..."

### ISSUE THREAD

**Issue by xsxWang** [LibreDWG/libredwg#1034]
write line object to dwg file,then open file with autoCAD 2007/2010..., "The recover command may be able to restore..."
![cad-err-1](https://github.com/user-attachments/assets/ba842ac3-0fb2-4726-bf2f-c10f79b38262)
![cad-err-2](https://github.com/user-attachments/assets/aaa668bc-8a52-442f-9ca6-f4a3a0354a2b)
![cad-err-3](https://github.com/user-attachments/assets/f1524396-89ec-4dc5-b4c4-af9a46eac0b3)
@rurban I was wondering if you could tell me the reason and please show me some related code. thks

**Comment by rurban** [comment]
The reason is that libredwg cannot yet convert to r2000 without recovery errors in about 30% of all dwg's.
It works as documented and expected.
