### ISSUE TITLE
clang: error: argument unused during compilation: '-fstack-clash-protection' [-Werror,-Wunused-command-line-argument]

### ISSUE THREAD

**Issue by chen6857** [LibreDWG/libredwg#1038]
System: macOS 14.2.1 
Chip: Intel

I open by IDE Clion, I want to debug   'programs/dwgread.c', then
clang: error: argument unused during compilation: '-fstack-clash-protection' [-Werror,-Wunused-command-line-argument]

 
<img width="1090" alt="image" src="https://github.com/user-attachments/assets/b59d875d-0c6d-4752-90cd-809024759729">

**Comment by chen6857** [comment]
I close this
    if (HAVE_C_FSTACK_CLASH_PROTECTION)
#      clang: error: argument unused during compilation: '-fstack-clash-protection' [-Werror,-Wunused-command-line-argument]
#      add_compile_options(-fstack-clash-protection)
      add_link_options(-fstack-clash-protection)
    endif()

**Comment by chen6857** [comment]
I close this
    if (HAVE_C_FSTACK_CLASH_PROTECTION)
#      mac上报错
#      clang: error: argument unused during compilation: '-fstack-clash-protection' [-Werror,-Wunused-command-line-argument]
#      add_compile_options(-fstack-clash-protection)
      add_link_options(-fstack-clash-protection)
    endif()

**Comment by qwuip789** [comment]
I also encountered the same problem. Commenting out this line shouldn't have any impact, right?

**Comment by chen6857** [comment]
> I also encountered the same problem. Commenting out this line shouldn't have any impact, right?
可以参考我这个配置文件，改了一些设置，对比下看看。
[CMakeLists.txt](https://github.com/user-attachments/files/18280286/CMakeLists.txt)
