### ISSUE TITLE
There are several shortcomings with dwgbmp

### ISSUE THREAD

**Issue by dotoritos-kim** [LibreDWG/libredwg#1046]
There are several shortcomings with dwgbmp:

It doesn't support resizing.
It cannot read DXF files. I noticed there was a previously closed PR related to this feature. Are there any future plans regarding this?
I would like to know your thoughts or plans on addressing these issues. Additionally, how do you suggest solving the resizing problem mentioned in point 1?

**Comment by rurban** [comment]
> There are several shortcomings with dwgbmp:
> 
> It doesn't support resizing

Use an image resize tool then. 

. It cannot read DXF files. I noticed there was a previously closed PR related to this feature. Are there any future plans regarding this? 

There is no plan to create images when they dont exist, no. you might try create one from a svg. 


I would like to know your thoughts or plans on addressing these issues. Additionally, how do you suggest solving the resizing problem mentioned in point 1?
