### ISSUE TITLE
Invalid HATCH.curve_type 0

### ISSUE THREAD

**Issue by timoria21** [LibreDWG/libredwg#1047]
In the attached file, there is an error reading the contours of the Hatch with handle 884. 

The log reports: "ERROR: Invalid HATCH.curve_type 0"

[example.zip](https://github.com/user-attachments/files/17959316/example.zip)

**Comment by michal-josef-spacek** [comment]
@rurban Could you merge this patch?

**Comment by timoria21** [comment]
It works, thank you!
