### ISSUE TITLE
nonsense mix of macros

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#1056]
There are macros in src/dec_macros.h:
* SUB_FIELD_VECTOR_N
* SUB_FIELD_VECTOR_INL

and the same macros in src/spec.h:
* SUB_FIELD_VECTOR_N
* SUB_FIELD_VECTOR_INL

When I need to use src/spec.h/SUB_FIELD_VECTOR_INL macro in dwg.spec, there is an issue.
src/decode.c includes src/dec_macros.h and src/spec.h is included after from src/dwg.spec.

**Comment by michal-josef-spacek** [comment]
Usage of SUB_FIELD_VECTOR_INL is in:
* src/dwg.spec - Ok
* src/2ndheader.spec - Ok
* src/in_json.c - commented, Ok

Usage of SUB_FIELD_VECTOR_N
* src/dwg.spec - Ok
* src/out_json.c - Own definition - Ok

**Comment by rurban** [comment]
The decode variants are allocating, the others may not.
