### ISSUE TITLE
dwg2dxf ustable class object 0x481

### ISSUE THREAD

**Issue by mindreaderlupo** [LibreDWG/libredwg#1060]
[arc_2000.zip](https://github.com/user-attachments/files/18208124/arc_2000.zip)

PS C:\Users\felix\OneDrive\Documents\cad> dwg2dxf arc_2000.dwg
Reading DWG file arc_2000.dwg
Warning: Unstable Class object 501 MATERIAL (0x481) 15/0
Warning: Unstable Class object 501 MATERIAL (0x481) 23/0
Warning: Unstable Class object 501 MATERIAL (0x481) 31/0
Warning: Unstable Class object 504 TABLESTYLE (0xfff) 99/0
Warning: Unstable Class object 505 MLEADERSTYLE (0xfff) 101/0
Warning: Object handle not found 603/0x25B
Writing DXF file arc_2000.dxf
Warning: Unstable Class object 501 MATERIAL (0x481) 15/11
Warning: Unstable Class object 501 MATERIAL (0x481) 23/19
Warning: Unstable Class object 501 MATERIAL (0x481) 31/21
Warning: Unstable Class object 504 TABLESTYLE (0xfff) 99/65
Warning: Unstable Class object 505 MLEADERSTYLE (0xfff) 101/67

I tried to convert a very simple dwg to dxf and get always errors and the dxf file is not readable. 
I tried it on Windows and in a Linux docker Container.

My System is win11 (ARM)

What could help here?

Thanks and BR
Felix

**Comment by rurban** [comment]
> What could help here?

Making them stable. I.e. Spec fixes. We do have enough testcases of these. See also the docs
