### ISSUE TITLE
nullpointer in out_geojson.c

### ISSUE THREAD

**Issue by UmlauteUeberall** [LibreDWG/libredwg#107]
I found a nullpointer at out_geojson.c line 391
hdr might be NULL, even if error is not set.
My dirty hack was:

`if (!error && hdr && hdr->type == DWG_TYPE_BLOCK_HEADER)`

the problem lies somewhere in dwg_ref_get_object

**Comment by UmlauteUeberall** [comment]
maybe something like this?
dwg_api.c line 21131:
```
dwg_ref_get_object (const dwg_object_ref *restrict ref, int *restrict error)
{
  if (ref)
    {
      *error = 0;
	  if (!ref->obj)
		*error = 1;
      return ref->obj;
    }
  else
    {
      *error = 1;
      LOG_ERROR ("%s: empty ref", __FUNCTION__)
      return NULL;
    }
}
```

**Comment by rurban** [comment]
Yes, something like this. Thanks

**Comment by UmlauteUeberall** [comment]
sorry, i forgot the brackets
