### ISSUE TITLE
json - nan in GEODATA field

### ISSUE THREAD

**Issue by UmlauteUeberall** [LibreDWG/libredwg#108]
trying to parse an normal json file I found nan-values in GEODATAs design_pt, using "NaN" should solve this

**Comment by rurban** [comment]
I don't quite understand. NaN in the src code somewhere?  NaN appears very often with wrongly parsed objects.

**Comment by rurban** [comment]
Or do you mean we should translate nan to "NaN" in json output?

**Comment by UmlauteUeberall** [comment]
Exactly, that would solve some parsers problems, since "nan" is often not recognised.

**Comment by rurban** [comment]
I found out that I have no single DWG with GEODATA objects to fix this. I just implemented it from scratch. Can you send me one per email?

**Comment by UmlauteUeberall** [comment]
I am trying to get free the file I used, sorry for the inconvenience

**Comment by rurban** [comment]
You can delete all other entities, I just need a GEODATA object. I'll also not publish it anywhere.

**Comment by rurban** [comment]
Fixed this problem for the unstable GEODATA object.
Also disable printing invalid nan values on release versions (i.e. no git checkout)
