### ISSUE TITLE
Invalid reading of enities with AcDbColor handles

### ISSUE THREAD

**Issue by normwill-beast** [LibreDWG/libredwg#111]
Hi,

It looks like entities are not read correctly when they include a handle to a color. From the DWG technical specification it looks like the handle does not follow the color flags and index. Below is an extract from the spec:

0x4000: has AcDbColor reference (0x8000 is also set in this case).
The handle to the color is written in the handle stream.

It says that the handle is written in the handle stream, not that it follows...

See attached file with a LWPOLYLINE with color handle

[polyline test.zip](https://github.com/LibreDWG/libredwg/files/3349904/polyline.test.zip)

**Comment by normwill-beast** [comment]
Further observation: The reading of the color handle later is also wrong (in common_entity_handle_data.spec). It checks 
   (FIELD_VALUE(color.flag) & 0x40))
It should read 
   (FIELD_VALUE(color.flag) & 0x4000) 
because the value has not be shifted right (like in 'common_entity_data.spec')

**Comment by rurban** [comment]
Yes, true. color.handle is wrong, needs to be read from hdl_dat. Just fixed that.
But the flag is seperated from the index, right shifted. so common_entity_handle_data.spec is correct.
The main error is that bit_read_ENC and FIELD_ENC is still not used.
Working on that now
