### ISSUE TITLE
Incorrect object address set

### ISSUE THREAD

**Issue by normwill-beast** [LibreDWG/libredwg#112]
It looks like setting 'obj->address' is wrong for R_2010+ files. The data read for 'handlestream_size' in R_2010+ files should not be counted in the object size.

Currently in decode.c:

  obj->address = dat->byte;
  end_address = obj->address + obj->size; /* (calculate the bitsize) */
  SINCE (R_2010)
  {
    obj->handlestream_size = bit_read_UMC (dat);
    LOG_INFO (", Hdlsize: " FORMAT_UMC, obj->handlestream_size);
    obj->bitsize = obj->size * 8 - obj->handlestream_size;
    obj->type = bit_read_BOT (dat);
  }
  else { obj->type = bit_read_BS (dat); }

Should be changed to:

  SINCE (R_2010)
  {
    /* This is not counted in the object size */
    obj->handlestream_size = bit_read_UMC (dat);
    LOG_INFO (", Hdlsize: " FORMAT_UMC, obj->handlestream_size);
    obj->bitsize = obj->size * 8 - obj->handlestream_size;
  }
  
  obj->address = dat->byte;
  end_address = obj->address + obj->size; /* (calculate the bitsize) */

  SINCE (R_2010)
  {
    obj->type = bit_read_BOT (dat);
  }
  else { obj->type = bit_read_BS (dat); }

This however has further knock on effects. It looks like some pieces of code have been modified in order to 'fix' the error.

1) The setting of 'obj->hdlpos' and 'obj->handle_offset' should no longer have '+= 8' in functions dwg_decode_entity() and dwg_decode_object(). (it has already been tagged 'FIXME')

2) The reading of BLOCK_CONTROL in dwg.spec should remove the 'UNTIL (R_2007)'. The paper_space block can always be read.
    I.e., change
    
      UNTIL (R_2007) {
        FIELD_HANDLE (paper_space, 3, 0);
      }
  
    to
  
      FIELD_HANDLE (paper_space, 3, 0);

3) There may be more....

**Comment by rurban** [comment]
Yep, this is a big one. Looks much better now.
