### ISSUE TITLE
dwgread randomly crashes on same file (windows 7 64 bit)

### ISSUE THREAD

**Issue by adipose** [LibreDWG/libredwg#125]
I have a reproducible crash that happens only intermittently on the same file.  

dwgread.exe -v3 trouble.dwg

No error is reported--the output simply stops mid print and crashes with return code 1.  If I run the same file again, I may get the same result, or else it may succeed.

On this file the output (including stderr) is about 160MB when it succeeds, and random when it fails.  

Here is the tail of one output of it just stopping:

> 
> plotstyle_flags: 0 [BB 0]
> material_flags: 0 [BB 0]
> shadow_flags: 0x 0 [RC 284]
> has_full_visualstyle: 0 [B 0]
> has_face_visualstyle: 0 [B 0]
> has_edge_visualstyle: 0 [B 0]
> invisible: 1 [BS 60]
> linewt: 0x1d [RC 370]
> flag: 2 [BS 70]
> thickness: 1.627113 [BD 39]
> num_points: 9 [BL 90]
> points[0]: (6.922552, -0.516608) [RD 10]
> points[1]: (6.881224, -0.516608) [DD 10]
> points[2]: (6.839895, -0.495944) [DD 10]
> points[3]: (6.819231, -0.454615) [DD 10]
> points[4]

Is there anything I can do better to debug what's crashing it?  I have the file available, but it is private, so I'd prefer to do the debugging myself if possible.

**Comment by rurban** [comment]
debug it with gdb. use latest master.
