### ISSUE TITLE
cannot create regular file

### ISSUE THREAD

**Issue by SpeedrunnerG55** [LibreDWG/libredwg#128]
os: Ubuntu 18.04

went through the installation instructions and got the make install 
and then this is my output.
not sure what exactly is going on but every step beyond this gives nothing but errors

`make install
make  install-recursive
make[1]: Entering directory '/home/speed/Downloads/libredwg-0.8.1969'
Making install in src
make[2]: Entering directory '/home/speed/Downloads/libredwg-0.8.1969/src'
make[3]: Entering directory '/home/speed/Downloads/libredwg-0.8.1969/src'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   libredwg.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libredwg.so.0.0.8 /usr/local/lib/libredwg.so.0.0.8
/usr/bin/install: cannot create regular file '/usr/local/lib/libredwg.so.0.0.8': Permission denied
Makefile:520: recipe for target 'install-libLTLIBRARIES' failed
make[3]: *** [install-libLTLIBRARIES] Error 1
make[3]: Leaving directory '/home/speed/Downloads/libredwg-0.8.1969/src'
Makefile:709: recipe for target 'install-am' failed
make[2]: *** [install-am] Error 2
make[2]: Leaving directory '/home/speed/Downloads/libredwg-0.8.1969/src'
Makefile:589: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/speed/Downloads/libredwg-0.8.1969'
Makefile:876: recipe for target 'install' failed
make: *** [install] Error 2
`

EDIT: 
i ran make check and 1 of 1 test failed

> ===================
All 47 tests passed
===================
make[4]: Leaving directory '/home/speed/Downloads/libredwg-0.8.1969/test/unit-testing'
make[3]: Leaving directory '/home/speed/Downloads/libredwg-0.8.1969/test/unit-testing'
Making check in xmlsuite
make[3]: Entering directory '/home/speed/Downloads/libredwg-0.8.1969/test/xmlsuite'
make  testsuite
make[4]: Entering directory '/home/speed/Downloads/libredwg-0.8.1969/test/xmlsuite'
  CC       testsuite.o
  CCLD     testsuite
make[4]: Leaving directory '/home/speed/Downloads/libredwg-0.8.1969/test/xmlsuite'
make  check-TESTS
make[4]: Entering directory '/home/speed/Downloads/libredwg-0.8.1969/test/xmlsuite'
import-im6.q16: not authorized `os' @ error/constitute.c/WriteImage/1037.
import-im6.q16: not authorized `sys' @ error/constitute.c/WriteImage/1037.
./check.py: line 5: syntax error near unexpected token `('
./check.py: line 5: `srcdir = os.path.dirname(__file__)'
FAIL: check.py
=================================
1 of 1 test failed
Please report to libredwg@gnu.org
=================================
Makefile:552: recipe for target 'check-TESTS' failed
make[4]: *** [check-TESTS] Error 1
make[4]: Leaving directory '/home/speed/Downloads/libredwg-0.8.1969/test/xmlsuite'
Makefile:675: recipe for target 'check-am' failed
make[3]: *** [check-am] Error 2
make[3]: Leaving directory '/home/speed/Downloads/libredwg-0.8.1969/test/xmlsuite'
Makefile:753: recipe for target 'check-recursive' failed
make[2]: *** [check-recursive] Error 1
make[2]: Leaving directory '/home/speed/Downloads/libredwg-0.8.1969/test'
Makefile:589: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/speed/Downloads/libredwg-0.8.1969'
Makefile:868: recipe for target 'check' failed
make: *** [check] Error 2

**Comment by rurban** [comment]
cannot create regular file '/usr/local/lib/libredwg.so.0.0.8': Permission denied
should explain it. 

use `sudo make install`
