### ISSUE TITLE
Crash files

### ISSUE THREAD

**Issue by yarylka** [LibreDWG/libredwg#132]
Parsing these files leads to a crash.

[CRASH-FILES.zip](https://github.com/LibreDWG/libredwg/files/3504842/CRASH-FILES.zip)

**Comment by rurban** [comment]
* 00.dwg is related to #93 (fail to decode big non-2007 sections)
* 08.dwg fails on GROUP.num_handles (overflow). It also has some corrupt AcDbObjects section entries, probably the same #93 issue.
* 12.dwg seem to have the #93 issue. AcDbObjects look ok, but some late obj->address are clearly wrong.

**Comment by rurban** [comment]
Fixed the #93 issue with c0163ccc71bcd6755ab1f6929b947bcd9ea67c43
Now just 08.dwg fails
