### ISSUE TITLE
dwg2SVG is ignoring all polylines

### ISSUE THREAD

**Issue by ITaluone** [LibreDWG/libredwg#137]
Hi

dwg2svg is constantly ignoring all polylines in various dwg files.

is that right? Am i missing something?

**Comment by rurban** [comment]
You are right. Only very few entities are emitted for SVG yet. Not just plines, also many others are missing.

**Comment by ITaluone** [comment]
Ok, so is this on your 2do-list? Or do you have an idea how i get around this?

**Comment by rurban** [comment]
Sure, it's an my TODO list. But first there are the most basic features missing I'm working on. It would be also trivial to add for any newbie.

**Comment by rurban** [comment]
It has now all POLYLINE_2D and LWPOLYLINE entities, even converted from OCS (i.e. different extrusion vectors)
