### ISSUE TITLE
dwg2SVG exported content will always prompt an error

### ISSUE THREAD

**Issue by yoyomule** [LibreDWG/libredwg#149]
Hello, test dwg2SVG（0.8.2）, the exported content will always prompt an error, is it wrong with me? But using dwg2dxf is normal.
Such as tips：
![image](https://user-images.githubusercontent.com/10000818/65845395-b12cff00-e36c-11e9-8c4d-7d7c0d9d0faa.png)
[libredwg test.zip](https://github.com/LibreDWG/libredwg/files/3668605/libredwg.test.zip)

Thanks.

**Comment by rurban** [comment]
I haven't touched this since ages. Will check

**Comment by rurban** [comment]
Fixed with f0dfcf5460b9bdc6ec75e8fe2ff6a4b8990b6049
Thanks for the testcase with unicode text!
