### ISSUE TITLE
The pre-release for windows cannot run

### ISSUE THREAD

**Issue by eryar** [LibreDWG/libredwg#15]
The pre-release LibreDWG for Windows cannot run, see follow picture:

![image](https://user-images.githubusercontent.com/8439181/41037875-25f9dc70-69c7-11e8-8ec0-af753913b2ee.png)

**Comment by eryar** [comment]
Hi Reini Urban,

I used the depends to check the dwgread.exe, and find it has not dependency with the libredwg-0.dll:
![image](https://user-images.githubusercontent.com/8439181/41039312-a401983e-69cb-11e8-8501-2cbe8ca1dfe4.png)

Other *.exe have the same problem. Do you use the static library for libredwg?

Best Regards,
Shing Liu

**Comment by rurban** [comment]
Nope, it should be the dynamic dll. All the tests on appveyor do run correctly.
See `.appveyor.yml` of the build recipe, and `build-aux/appveyor-deploy.bat` for the geneartion of the zip.
I'll check the logs at https://ci.appveyor.com/project/rurban/libredwg/history

**Comment by eryar** [comment]
OK.

I will try to compile libredwg on Windows and have a test.

**Comment by rurban** [comment]
Yes please, the logs do look ok to me.
I'll try to revive my windows machine in the meantime.

**Comment by eryar** [comment]
The 0.4.660 still the same problem and all the *.exe files are the same size:
![image](https://user-images.githubusercontent.com/8439181/41043661-fb05b8f8-69d6-11e8-8866-c2c106ba1a0b.png)
