### ISSUE TITLE
How to find WINDOWS source code

### ISSUE THREAD

**Issue by 15608082968** [LibreDWG/libredwg#155]
I am not an experienced programmer.I am confused, why can you provide DLL files, but do not provide WINDOWS source code? I really need to use this library on WINDOWS

**Comment by rurban** [comment]
Esp. for Windows users there are also binary releases. The source code is in the tar.* files, the binaries in the win*.zip files. See https://github.com/LibreDWG/libredwg/releases/tag/0.9
