### ISSUE TITLE
fonts and some erro.

### ISSUE THREAD

**Issue by yoyomule** [LibreDWG/libredwg#156]
Hello, I tested version 0.9 and I have the following problems:
I have provided two dwg files, tmp1.dwg and tmp2.dwg.
The tmp1.dwg file contains the shx font. The text content is well preserved when exporting, but all the characters are replaced with truetype fonts. So after dwg is converted into svg, many style changes have occurred. Can it still be shx font style restore?
tmp2.dwg contains a small amount of drawing content, but after switching out to svg, it does not see any content. I tried to use dwg2dxf to convert to dxf. At this time, I get the following error message.
![QQ截图20191015223202](https://user-images.githubusercontent.com/10000818/66841212-eefc6b00-ef9b-11e9-8955-3645a6269d7f.png)
[libredwg test.zip](https://github.com/LibreDWG/libredwg/files/3729861/libredwg.test.zip)
Thanks.

**Comment by rurban** [comment]
* fonts: we don't yet translate font-styles to svg font-families. currently there's only Verdana. But I could change that to use Courier for all non-ttf fonts, and Verdana for ttf fonts. There's no SIMPLEX or COMPLEX in svg imho.

* error messages. That's no problem. some objects cannot be read yet. svg only translates a tiny percentage of all entities also.

**Comment by yoyomule** [comment]
> * L
Thanks.
Is it possible to turn shx into a symbol instead of a text so that it can be restored. You can add a choice when exporting.

**Comment by rurban** [comment]
Unfortunately not. I don['t know a way to convert a SHX into blocks of polylines, maybe there's one.
