### ISSUE TITLE
How to port library for Android OS

### ISSUE THREAD

**Issue by phammanhdam** [LibreDWG/libredwg#157]
I am looking for a library that allows reading DWG files on Android.  And I found this library, but it was written in C ++ and I don't know how to port for Android.  I am very grateful if anyone can help to use on Android.

Thank you very much,

**Comment by rurban** [comment]
There's no such thing as porting to Android. LibreDWG doesn't yet work on big-endian processors, and some DWG's are too big to be processed by 32bit processors. Others than that LibreDWG does work on Android.

**Comment by rurban** [comment]
Yes, LibreDWG
