### ISSUE TITLE
Potential Null dereference

### ISSUE THREAD

**Issue by ManSoSec** [LibreDWG/libredwg#172]
I think a null check on `dwg->dwg_class` is missing here:

https://github.com/LibreDWG/libredwg/blob/785df5f3b9b38dd383fa205791aedd9cb9302b4c/src/print.c#L588-L594

While it is done here, which is a similar cases:

https://github.com/LibreDWG/libredwg/blob/785df5f3b9b38dd383fa205791aedd9cb9302b4c/src/free.c#L727-L732

**Comment by rurban** [comment]
make scan-build complains about 6 of those.

**Comment by rurban** [comment]
Only with free we could have freed dwg->dwg_class already. Will not happen with print, where num_classes will be 0 then.
