### ISSUE TITLE
Type casting inconsistency

### ISSUE THREAD

**Issue by ManSoSec** [LibreDWG/libredwg#174]
https://github.com/LibreDWG/libredwg/blob/785df5f3b9b38dd383fa205791aedd9cb9302b4c/src/decode.c#L2552

https://github.com/LibreDWG/libredwg/blob/785df5f3b9b38dd383fa205791aedd9cb9302b4c/src/decode_r2007.c#L1594

Is a type casting (int) missed?

**Comment by rurban** [comment]
We should rather zero-extend to long both sides here, to avoid overflows. Thanks. Done in 631bbacb3e18403db1015ef4063c3d19e9c8e11a
