### ISSUE TITLE
can't read Chinese layer name

### ISSUE THREAD

**Issue by wrsjhhe** [LibreDWG/libredwg#177]
I read a dwg file which layer name is all Chinese.
the result of reading is error codes,
is there any way to convert them to normal?

**Comment by rurban** [comment]
Yes, use extnames. 
Eg in dwglayer use the -x flag, or see there how to extract the EXTNAME.

**Comment by wrsjhhe** [comment]
> 
> 
> Yes, use extnames.
> Eg in dwglayer use the -x flag, or see there how to extract the EXTNAME.

thinks,I converted char to wchar_t,and It worked
