### ISSUE TITLE
Missing NULL check before passing to free

### ISSUE THREAD

**Issue by ManSoSec** [LibreDWG/libredwg#206]
There is an inconsistency here:

https://github.com/LibreDWG/libredwg/blob/0a491e5fa0bb7bc7133e4c247fcc9e6a2c3b0166/src/decode.c#L2806-L2808

https://github.com/LibreDWG/libredwg/blob/0a491e5fa0bb7bc7133e4c247fcc9e6a2c3b0166/src/decode_r2007.c#L1701-L1705

Looks like two checks are missing. But, on the other hand, If ptr is a null pointer, no action occurs in free.

**Comment by rurban** [comment]
Yes, but it's harmless. free accepts NULL args.
