### ISSUE TITLE
Missing memset and zero outing

### ISSUE THREAD

**Issue by ManSoSec** [LibreDWG/libredwg#207]
I feel this is mostly related to code quality:

https://github.com/LibreDWG/libredwg/blob/0a491e5fa0bb7bc7133e4c247fcc9e6a2c3b0166/programs/dwg2dxf.c#L245-L253

https://github.com/LibreDWG/libredwg/blob/0a491e5fa0bb7bc7133e4c247fcc9e6a2c3b0166/programs/dxf2dwg.c#L245-L252

**Comment by rurban** [comment]
Nope. The first reads from a DWG, the second writes to DWG. 
In the second the memzero is done in the dxf_read_file() call.
