### ISSUE TITLE
GeoJSON exporting : error in json format

### ISSUE THREAD

**Issue by yossefaz** [LibreDWG/libredwg#209]
When using the dwgread command and export a dwg to json format, the json exported add an extra comma which is a non-valid json :

here is the command that i used : 

dwgread test.dwg -O GeoJson test.json 

{
	"type": "FeatureCollection",
	"features": [{
			"type": "Feature",
			"properties": {
				"SubClasses": "AcDbObject : AcDbGeoData",
				"EntityHandle": "4"
			} , <=== EXTRA COMMA
		}, 
}

**Comment by yossefazoulay** [comment]
another issue is that no error when exporting to GeoJSON even if dwg is corrupted : 

{
  "type": "FeatureCollection",
  "features":   ], <====
  "geocoding":   {
    "creation_date": "2020-03-09",
    "generator":     {
      "author":       {
        "name": "dwgread"
      },
      "package": "LibreDWG",
      "version": "0.10.1.364_953cc"
    }
  }
}

**Comment by rurban** [comment]
Can you send me the DWG for these errors? Needs to be fixed.

Yossef AZOULAY <notifications@github.com> schrieb am Di., 10. März 2020,
12:50:

**Comment by yossefaz** [comment]
Here is a Google drive link to two dwg files :

2010_1.dwg => for the first error (extra comma)

2010_2.dwg => for the second error (corrupted file, will export to json anyway)

I also joined here the output json file

https://drive.google.com/drive/folders/1NRqt1OARxFYXFybML1uv7Ze1f6ElHc-O?usp=sharing

**Comment by rurban** [comment]
Wonderful! The first testcase with an GEODATA object. Thanks a lot.
