### ISSUE TITLE
[SOLVED] Installing libredwg on windows to use it within FreeCAD

### ISSUE THREAD

**Issue by carlopav** [LibreDWG/libredwg#218]
Hello @rurban,
sorry for the simple question: i'm a complete newby. I downloaded the windows nightly at https://github.com/LibreDWG/libredwg/releases.
But I have no idea on where i should put the files to make them available in FreeCAD (EDIT and use the functions through its python console).
Any avice?
thx :)

carlo

**Comment by rurban** [comment]
Nope, haven't tried the new FreeCAD yet. Please ask over there.

**Comment by carlopav** [comment]
I succeded opening it from FreeCAD, but it gives me the same error that occurs when I try to execute it from windows command prompt:
"Cannot start program because libssp-0.dll is not present on the computer. Try to re-install the program".
I succeded to run it only from "Anaconda Prompt (Anaconda3)".
Any advice?

**Comment by rurban** [comment]
Try to find the matching mingw libssp DLL and copy it to the DWG exe's. I might include it later into the zip. Mingw frequently changes deps.

**Comment by carlopav** [comment]
Great! I downloaded the DLL and placed into the exe's folder and it works.
