### ISSUE TITLE
How to write TEXT with ttf font in CAD software?

### ISSUE THREAD

**Issue by zhengf312** [LibreDWG/libredwg#240]
I have a dwg file, this file contains a lot of Chinese characters.

If I convert all the Chinese characters into vector lines(eg. line, polyline, spline), it will be extremely slow.

I heard that other CAD software uses ttf font to process， not vector lines.

But abot how to write TEXT with ttf font in CAD software,  I have no experience in this area, can you provide a link to related knowledge or some ideas?

Thank you very much.

**Comment by rurban** [comment]
Nope, sorry.
Use Google how to setup ttf fonts

zhengf312 <notifications@github.com> schrieb am Fr., 3. Juli 2020, 06:09:
