### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by ntnHome** [LibreDWG/libredwg#254]
I git cloned this reporitory. As per README, I tried doing
`$ sh ./autogen.sh`
I get an error 'autoreconf not found' at line 24

If I ignore this and go to next line, I cannot find 'configure' in the folder.

Any help is greatly appreciated.

**Comment by rurban** [comment]
install autoreconf, or get a release tarball, which does not need autoreconf.

**Comment by ntnHome** [comment]
Thank you
