### ISSUE TITLE
Invalid parameter in object TEXT alignment_pt (dwg.spec)

### ISSUE THREAD

**Issue by ZalivahaAM** [LibreDWG/libredwg#264]
Good day.
I suggest replacing in the dwg.spec file
code
FIELD_2DD (alignment_pt, 10.0, 20.0, 11);
on the
FIELD_2DD (alignment_pt, _obj-> ins_pt.x, _obj-> ins_pt.y, 11);
How is done in libdxfrw library
Otherwise, the text object receives an invalid ins_pt value.
https://cloud.mail.ru/public/4nma/2pWfz8P6S

And in the RESBUF_VALUE_TYPE enumeration, if possible, then rename VT_BOOL = 10
Since it conflicts with the wtypes.h file VT_BOOL = 11
C: /Qt/Tools/mingw810_64/x86_64-w64-mingw32/include/wtypes.h

Thank

**Comment by rurban** [comment]
Thanks

**Comment by rurban** [comment]
Fixed with 02707271c61ecb97d113c2b5320758157be10e43 and 7e8725315e262e505693b43285022214f4738c63
