### ISSUE TITLE
dwg2SVG is creating empty file

### ISSUE THREAD

**Issue by maciekglowacki** [LibreDWG/libredwg#267]
Hi, I tried using dwg2SVG commandline utility, however it failed with all of my dwg files resulting in generating empty svg files. 

Is that a known problem?

**Comment by rurban** [comment]
No, all the tests pass and are even tested for correctness with a SVG linter. Please describe the problem better.

**Comment by maciekglowacki** [comment]
I attach logs from -v1 used to convert these files. I want to point out that I converted the same files to svgs using commercial program and the conversion was successful. 

![dxf2svgerror1](https://user-images.githubusercontent.com/29459845/90774481-db2a3f80-e2f7-11ea-9e67-b314b662f729.png)
![dxf2svgerror2](https://user-images.githubusercontent.com/29459845/90774553-f432f080-e2f7-11ea-88ec-48359a074f21.png)

In this case conversion resulted in empty svg file.

**Comment by rurban** [comment]
No screenshots, attach the dwg files zipped please.
This seems to be an unsupported DWG file, with broken sections. Maybe related to #144

**Comment by maciekglowacki** [comment]
Zipped files: [dwg.zip](https://github.com/LibreDWG/libredwg/files/5107334/dwg.zip)

Can I repair these files on my own?

**Comment by maciekglowacki** [comment]
Thank you very much for your help. I will stay with this non-free converter for now :D

**Comment by rurban** [comment]
1. Duplicate of GH #144
2. the other consists only of proprietary entities
