### ISSUE TITLE
Dockfiler building crashes with SEGV in dxf_test

### ISSUE THREAD

**Issue by Begalov** [LibreDWG/libredwg#268]
Tried to build Dockerfile of cloned repo
```
$ docker build -t libredwg .
...
HELIX 1BF ../../test/test-data/2018/Helix.dwg
not ok 1        # HELIX.radius: 6.827832 <=> "0.0" [BD 40] REAL
ok 2    # HELIX.major_version: 31
ok 3    # HELIX.maint_version: 8
ok 4    # HELIX.turns: 3.000000
ok 5    # HELIX.handedness: 1
Exception 0xc0000005 0x0 0xc000638000 0x7e13a4f9
PC=0x7e13a4f9
signal arrived during external code execution
```
and docker crashes when handling the SEGV

Full console output https://paste.debian.net/1162131/

**Comment by rurban** [comment]
First: This Dockerfile misses the pcre2 dependency.

Second: The HELIX unit-tests fails, which should be ignored, because it is not stable.
But in the docker case the SEGV is fatal, whilst with testing in the shell it is not. I have no idea on special such docker signal behaviors.

**Comment by rurban** [comment]
podman works fine, just docker is broken.

**Comment by rurban** [comment]
Even without docker it crashes now in dxf_test at 2018/Helix.dwg. See eg https://travis-ci.org/github/LibreDWG/libredwg/jobs/723376835
