### ISSUE TITLE
How tessellate 3D data?

### ISSUE THREAD

**Issue by jackcaron** [LibreDWG/libredwg#270]
So based on some information that I found (_particularly the SVG program_), for a 3D face, it looks like it can produce triangles or quads (_any other would be invalid_). Still, better info about the `invis_flags` would be useful here.

As for `solid`, where can I find documentation about all the fields, what it would represent in 3D and how to create triangles out of it?

Similar question for anything else that could create 3D solid data.

**Comment by rurban** [comment]
If you mean 3dsolid/acid data: The official acis documentation only.
The invis_flag is a bitmap which edge is invisible: see any DXF doc.

For tesselation, see any external tesselation library
