### ISSUE TITLE
DWG get file units

### ISSUE THREAD

**Issue by jackcaron** [LibreDWG/libredwg#276]
Is there a way to know in which unit the data is? Or what value do you have to multiply it to get meters (_that's something that exists for FBX_)? Or is it part of the standard?

I'm currently importing some meshes, Polyline PFace objects, and they all look fine, but there's too big (_our unit is meter_).

Thanks.

**EDIT**
I found `LUNITS` (linear), `AUNITS` (angular), and `INSUNITS` (drawing units). `LUNITS` doesn't mean much, it's always set to `2`, which means `Decimal`... not a useful information. And `INSUNITS` is set to `0`, which is unspecified.

**Comment by rurban** [comment]
Yes, it is somewhere else also. Give me a few hours to look it up.

**Comment by rurban** [comment]
It's in HEADER.Measurement, and since r2000 the integer value stored in the optional Template section.
(0 English/1 Metric)
