### ISSUE TITLE
Can add SDS(Simple Dynamic Strings) to the project

### ISSUE THREAD

**Issue by chensccode** [LibreDWG/libredwg#293]
I want to use the `SDS` tool to process strings, but I tried several times and couldn't compile. I don't know how to use it in the project. I want use `SDS` like `jsmn`, but failure.  I am not good at dealing with C language engineering. I need some help. Thanks.

[https://github.com/antirez/sds](url)

**Comment by rurban** [comment]
There's a work/strings branch, which is similar to SDS.
SDS is not really useful here, as we need seperate codepages and transformations.
See GH #245
