### ISSUE TITLE
dxf2json (similar way as dwg2json)

### ISSUE THREAD

**Issue by belmotek** [LibreDWG/libredwg#296]
Hi, Reini.
We use the tool dwg2json, is great to import dwg files in GauchoCAD. We miss some dxf2json in order to import DXF also.
¿Is planed dxf2json?
Regards.

**Comment by rurban** [comment]
dxf2json would be `dxf2dwg $file.dwg && dwgread -o $file.json $file.dwg`
Internally it would be the same. First import the DXF into a DWG, and then write a JSON.

**Comment by belmotek** [comment]
Ok, yes actually i do that. but now is only dxf v2000 right?

**Comment by rurban** [comment]
True. DXF can be written in every supported version, just DWG not. By going over the intermediate DWG we can only do v2000. This could be a good reason to create such a simple converter. 
But I have more important things to do now. Would be very simple to do based on some existing converter. Would take a PR, but will be deprecated (i.e. built in examples, but not packaged) once 2004-2018  can be written.
