### ISSUE TITLE
Support for DWG R2018 ?

### ISSUE THREAD

**Issue by jossefaz** [LibreDWG/libredwg#313]
Hi

I tried to dwg2dxf a 2018 dwg format.
The output dxf does not open correctly (it does not open at all and seems to be "corrupted" somehow)

As I saw in the documentation the library currently support only few of R2010+

Do you think that 2018+ will be available soon ?

If you want to try this file here is a [link](https://drive.google.com/drive/folders/1NRqt1OARxFYXFybML1uv7Ze1f6ElHc-O?usp=sharing) the file is called 2018_3.dwg

**Comment by rurban** [comment]
The docs are wrong. R2018 is supported, and r2018 is the latest known DWG format. (up to AutoCAD 2021)

I'll fix this dxf error, thanks for the testcase.

**Comment by rurban** [comment]
Cannot confirm. 2018_3.dxf converted with 0.12.1 dwg2dxf opens fine on my AutoCAD 2018. Without any warning.

**Comment by jossefaz** [comment]
Okay. Weird.
I'll check once again.

Thanks for your time and patience !

**Comment by rurban** [comment]
Maybe you tried with 0.12, not 0.12.1
