### ISSUE TITLE
Support rewrite for DWG 2018 files

### ISSUE THREAD

**Issue by khsergvl** [LibreDWG/libredwg#314]
Dear @rurban ,
I saw the last request for dwg 2018 support, however I'm still not sure if it is possible to rewrite let's say from dwg 2004 format to 2018 one? 
If 2018 rewrite is supported and only the issue with help https://github.com/LibreDWG/libredwg/blob/master/programs/dwgwrite.c#L62
I will be appreciated if you let me know.
Best regards

**Comment by rurban** [comment]
Ah, I misunderstood. 2018 write is not supported yet, only 2000 write, and 2018 read.
