### ISSUE TITLE
The exported SVG is wrong

### ISSUE THREAD

**Issue by wangxw0820** [LibreDWG/libredwg#328]
I use dwg2svg to export svg,then open it in chrome.There are some misinformation.
![image](https://user-images.githubusercontent.com/29654121/113824732-b31e1c80-97b2-11eb-8db8-22522a432286.png)

**Comment by rurban** [comment]
No negative x, y values? Strange. ok, easy to fix.
The rotation also, thanks

**Comment by rurban** [comment]
I fixed now the radius and rotation. The pathLength is still missing (if the ellipse is open)
