### ISSUE TITLE
The exported SVG lost its original color

### ISSUE THREAD

**Issue by wangxw0820** [LibreDWG/libredwg#331]
I exported DWG to SVG and found that it lost the original color

**Comment by abenson** [comment]
Duplicate of #328?

**Comment by rurban** [comment]
Can you attach the dwg (zipped)?

**Comment by wangxw0820** [comment]
I can't give it to you because of the copyright limitation of DWG, but I know the general reason. It may be that part of the drawing content is in the negative part of the coordinate system

**Comment by wangxw0820** [comment]
![image](https://user-images.githubusercontent.com/29654121/114113410-14f49880-9911-11eb-9cce-f78474444405.png)

**Comment by wangxw0820** [comment]
There's something wrong with my test
