### ISSUE TITLE
Using dwggrep to find all distinct geometry types (or subclasses) in dwg

### ISSUE THREAD

**Issue by YaroslavKormushyn** [LibreDWG/libredwg#337]
Hello!

I've found that `dwgfilter` is no longer in the program list and figured that `dwggrep` should be a replacement for it, then.

How would one query all geometry types in a dwg file e.g. Polyline, Polygon, MText, etc.?

If there's a better tool to help me achieve this, please advise.
So far I've been successful in converting the dwg to dxf and querying the dxf file using `ogrinfo`. This seems like an unnecessary overhead since we're able to read the dwg file directly.

**Comment by YaroslavKormushyn** [comment]
There's a [section in the documentation](https://www.gnu.org/software/libredwg/manual/LibreDWG.html#Programs) for `dwgfilter`, but I don't see that program available in the Windows x64 binaries.

**Comment by YaroslavKormushyn** [comment]
I've tried opening the `dwggrep.exe` and had missing dlls pop up. I believe you already fixed it in #103, but I don't see the dlls included anywhere in the zip of the [latest release](https://github.com/LibreDWG/libredwg/releases/tag/0.12.4).

<summary> Screenshots <details>

![image](https://user-images.githubusercontent.com/11539004/115512875-1c119400-a28b-11eb-817c-3cef6440d22d.png)

![image](https://user-images.githubusercontent.com/11539004/115512996-3f3c4380-a28b-11eb-9fdb-ec0f64997ec3.png)

</details>
</summary>

**Comment by YaroslavKormushyn** [comment]
1. So that means `dwgfilter` is only going to be available for machines running Linux?
2. Ok, that makes sense, but I thought they're going to be included in the package, since the other dependencies are there...

**Comment by rurban** [comment]
Add dwgfilter to the windows zip. Maybe find a bash => bat converter
