### ISSUE TITLE
ERROR: Failed to decode file: xyz.DWG 0xf7

### ISSUE THREAD

**Issue by aakhtar189** [LibreDWG/libredwg#338]
Failed to convert DWG to any format (JSON, dxf, SVG). 
this started happing after updating to the new release.

`Warning: checksum: 0x273e1245 (calculated) mismatch

ERROR: Skip section AcDb:AppInfoHistory with max decompression size 0x980 > 0x580
ERROR: Skip section AcDb:SummaryInfo with max decompression size 0x100 > 0x80
ERROR: Invalid section AcDb:SummaryInfo count or max decompression size. Sections: 1, Max size: 0
ERROR: Failed to read uncompressed SummaryInfo section
Warning: Object handle not found, 1/1 in 20270 objects
Warning: Object handle not found, 1/1 in 20270 objects
Warning: Object handle not found, 1/1 in 20270 objects
Warning: Object handle not found, 1/1 in 20270 objects
Warning: Object handle not found, 1/1 in 20270 objects
Warning: Object handle not found, 51/33 in 20270 objects
Warning: Object handle not found, 1/1 in 20270 objects
Warning: Object handle not found, 126/7E in 20270 objects
Warning: Object handle not found, 1/1 in 20270 objects
Warning: Object handle not found, 243/F3 in 20270 objects
Warning: Object handle not found, 1/1 in 20270 objects
Warning: Object handle not found, 10145/27A1 in 20270 objects
Warning: Object handle not found, 21/15 in 20270 objects
Warning: Object handle not found, 193/C1 in 20270 objects
Warning: Object handle not found, 35/23 in 20270 objects
Warning: Object handle not found, 221/DD in 20270 objects
Warning: Object handle not found, 15143/3B27 in 20270 objects
Warning: Object handle not found, 108/6C in 20270 objects
Warning: Object handle not found, 16130/3F02 in 20270 objects
Warning: Object handle not found, 208/D0 in 20270 objects
Warning: Object handle not found, 172/AC in 20270 objects
Warning: Object handle not found, 9347/2483 in 20270 objects
Warning: Object handle not found, 169/A9 in 20270 objects
Warning: Object handle not found, 225/E1 in 20270 objects
ERROR: Failed to decode file: CSL11-P0071098500-2020-04-01-DE-2_2013.DWG 0xf7`

**Comment by rurban** [comment]
Fixed in master
