### ISSUE TITLE
Errors decoding handles, wrong MC, UMC decoding

### ISSUE THREAD

**Issue by arturred** [LibreDWG/libredwg#386]
Hi 
I have problems decoding these files.
[err.zip](https://github.com/LibreDWG/libredwg/files/6676817/err.zip)
Looks like handle ids and offsets get wrong values. I think MC and UMC can be 8 bytes here. 
Please verify.
Thanks 
Artur

**Comment by rurban** [comment]
Indeed, very interesting cases. Thanks

**Comment by rurban** [comment]
Both libdxfrw (the original, and the new one from LibreCAD) neither can decode that.
