### ISSUE TITLE
Broken dwgadd

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#388]
dwgadd is unusable:
* Need of "\n" at begin of first string, sic. 
* issue with initial = 1 at begin and setting to intial after initialization
* No error message to stderr in each exit(1)
* Missing error in stderr in dwg_add_dat (&dwgp, &dat) != 0

**Comment by michal-josef-spacek** [comment]
There is another issue with creating of dwg file only with one entity.

Not working
```
point (0 0 0)
```
Working
```
point (0 0 0)
point (1 1 1)
```

Tested with `dwgadd -v9 --as r14 -o point.dwg point.dwgadd`

**Comment by rurban** [comment]
Oh my, this deserves a test case

**Comment by rurban** [comment]
There#s just #530 missing, which is a seperate preR13 issue (encode r13, r14 only)

**Comment by rurban** [comment]
Just added more fixes
