### ISSUE TITLE
./dwg.spec:1557:17: warning: format specifies type 'unsigned short' but the argument has type 'int' [-Wformat]

### ISSUE THREAD

**Issue by no-such-user** [LibreDWG/libredwg#396]
I'm seeing a couple of the above messages when compiling on a Mac. Does it matter?

./dwg.spec:7449:9: warning: format specifies type 'unsigned short' but the argument has type 'BITCODE_BL' (aka 'unsigned int') [-Wformat]

**Comment by no-such-user** [comment]
interestingly, all tests passed:
```
PASS: check-objects.pl
====================
All 247 tests passed
====================


```

but MAKEINFO failed on "make check", but not on "make". It had failed the same way on make, but I installed a newer textinfo

`brew install texinfo
`
Seems to be working, though.

**Comment by rurban** [comment]
What kind of compiler target exactly, 32bit or 64bit?

**Comment by no-such-user** [comment]
% ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... ./build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking git version... 0.12.4.4367_dirty
checking so version-info... 0:12:0
checking build system type... x86_64-apple-darwin20.6.0
checking host system type... x86_64-apple-darwin20.6.0
./configure: line 3888: PKG_PROG_PKG_CONFIG: command not found
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 786432
checking how to convert x86_64-apple-darwin20.6.0 file names to x86_64-apple-darwin20.6.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin20.6.0 file names to toolchain format... func_convert_file_noop
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin20.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for bash... /bin/sh
checking for inline... inline
checking for C/C++ restrict keyword... __restrict__
checking for PS_open_file in -lps... no
checking for pcre2_config_8 in -lpcre2-8... yes
checking for pcre2_config_16 in -lpcre2-16... yes
checking for newXMLEntity in -lxml2... no
./configure: line 13468: pkg-config: command not found
configure: WARNING: libxml-2.0 for test/xmlsuite not found
checking for egrep... (cached) /usr/bin/grep -E
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for stddef.h... yes
checking for unistd.h... (cached) yes
checking for malloc.h... no
checking for wchar.h... yes
checking for ctype.h... yes
checking for float.h... yes
checking for limits.h... yes
checking for libgen.h... yes
checking for getopt.h... yes
checking for alloca.h... yes
checking for valgrind/valgrind.h... no
checking for _Bool... yes
checking for stdbool.h that conforms to C99... yes
checking for strcasecmp header file... <strings.h>
checking for pcre2.h... yes
checking if pointers to integers require aligned access... no
checking for size_t... yes
checking for int16_t... yes
checking for uint16_t... yes
checking for int32_t... yes
checking for uint32_t... yes
checking for int64_t... yes
checking for uint64_t... yes
checking size of size_t... 8
checking size of wchar_t... 4
checking whether C compiler accepts -Werror=unknown-warning-option... yes
checking whether C compiler accepts -Wsuggest-attribute=format... no
checking whether C compiler accepts -mretpoline -DRETPOLINE... yes
checking whether C compiler accepts -fno-strict-aliasing... yes
checking whether C compiler accepts -fno-common... yes
checking whether C compiler accepts -fvisibility=hidden... yes
checking whether C compiler accepts -fno-semantic-interposition... no
checking whether C compiler accepts -fno-strict-aliasing... (cached) yes
checking whether C compiler accepts -fno-delete-null-pointer-checks... yes
checking whether C compiler accepts -fno-strict-overflow... yes
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -Wextra... yes
checking whether C compiler accepts -Wundef... yes
checking whether C compiler accepts -Wwrite-strings... yes
checking whether C compiler accepts -Wpointer-arith... yes
checking whether C compiler accepts -Wmissing-declarations... yes
checking whether C compiler accepts -Wredundant-decls... yes
checking whether C compiler accepts -Wno-unused-variable... yes
checking whether C compiler accepts -Wno-unused-parameter... yes
checking whether C compiler accepts -Wno-unused-but-set-variable... no
checking whether C compiler accepts -Wno-missing-field-initializers... yes
checking whether C compiler accepts -Wno-cast-align... yes
checking whether C compiler accepts -Wformat=2... yes
checking whether C compiler accepts -Wformat-nonliteral... yes
checking whether C compiler accepts -Wformat-security... yes
checking whether C compiler accepts -Wsign-compare... yes
checking whether C compiler accepts -Wstrict-aliasing... yes
checking whether C compiler accepts -Wshadow... yes
checking whether C compiler accepts -Winline... yes
checking whether C compiler accepts -Wpacked... yes
checking whether C compiler accepts -Wmissing-format-attribute... yes
checking whether C compiler accepts -Wmissing-noreturn... yes
checking whether C compiler accepts -Winit-self... yes
checking whether C compiler accepts -Wredundant-decls... (cached) yes
checking whether C compiler accepts -Wmissing-include-dirs... yes
checking whether C compiler accepts -Warray-bounds... yes
checking whether C compiler accepts -Wreturn-type... yes
checking whether C compiler accepts -Wswitch-enum... (cached) no
checking whether C compiler accepts -Wswitch-default... yes
checking whether C compiler accepts -Wduplicated-cond... no
checking whether C compiler accepts -Wduplicated-branches... no
checking whether C compiler accepts -Wlogical-op... no
checking whether C compiler accepts -Wrestrict... no
checking whether C compiler accepts -Wnull-dereference... yes
checking whether C compiler accepts -Wdouble-promotion... yes
checking whether C compiler accepts -Wchar-subscripts... yes
checking whether C compiler accepts -Wnested-externs... yes
checking whether C compiler accepts -Wmissing-prototypes... yes
checking whether C compiler accepts -Wstrict-prototypes... yes
checking whether C compiler accepts -Wdeclaration-after-statement... yes
checking whether C compiler accepts -Wimplicit-function-declaration... yes
checking whether C compiler accepts -Wold-style-definition... yes
checking whether C compiler accepts -Wjump-misses-init... no
checking whether C compiler accepts -Wno-error=unused-variable... yes
checking whether C compiler accepts -Wno-error=unused-parameter... yes
checking whether C compiler accepts -Wno-error=missing-field-initializers... yes
checking whether C compiler accepts -Wno-error=cast-align... yes
checking whether C compiler accepts -Werror=unknown-warning-option... (cached) yes
checking whether the linker accepts -Wl,--no-as-needed... no
checking whether the linker accepts -Wl,--fatal-warnings... no
checking whether the linker accepts -Wl,-fatal_warnings... yes
checking for __attribute__((visibility("default")))... yes
checking for __attribute__((gnu_format))... no
checking for __attribute__((ms_format))... no
checking for __attribute__((format))... yes
checking for __attribute__((malloc))... yes
checking for __attribute__((returns_nonnull))... yes
checking for __attribute__((noreturn))... yes
checking for GNU libc compatible malloc... (cached) yes
checking for GNU libc compatible realloc... (cached) yes
checking whether lstat correctly handles trailing slash... no
checking whether stat accepts an empty string... no
checking for working alloca.h... yes
checking for alloca... yes
checking for strtod... yes
checking for strdup... yes
checking for getopt_long... yes
checking for basename... yes
checking for strcasestr... yes
checking for scandir... yes
checking for floor... yes
checking for sqrt... yes
checking for floor in -lm... yes
checking for sqrt in -lm... yes
checking for sincos... no
checking for memchr... yes
checking for memmove... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strstr... yes
checking for strrchr... yes
checking for strtol... yes
checking for strtoul... yes
checking for strtoull... yes
checking for strnlen... yes
checking for memmem... yes
checking for wcslen... yes
checking for wcsnlen... yes
checking for wcscpy... yes
checking for wcscmp... yes
checking for wcsstr... yes
checking for sscanf_s... no
configure: WARNING: No secure sscanf_s found. dwgfuzz -add will produce false positives.
checking --enable-debug... no (default)
checking whether C compiler accepts -Werror... yes
checking whether to add -D_FORTIFY_SOURCE=2 to CPPFLAGS... yes
checking for restrict usability... 
no
checking --disable-write... no (default)
checking --enable-trace... no (default)
checking for setenv... yes
checking --disable-dxf... no (default)
checking --disable-json... no (default)
checking --disable-bindings... no (default)
checking for --enable-gcov... no (default)
checking for gperf... gperf
checking GPERF version... 300
checking for latest clang-format... indent
checking for --disable-python... check (default)
checking for swig... no
checking for swig3.0... no
configure: WARNING: SWIG is required for python bindings. disabled
checking for perl... /usr/bin/perl
checking PERL version... v5.30.2
checking for --with-perl-install=... site (default)
checking for picat... no
checking for parallel... no
checking for timeout... no
checking for makeinfo... ${SHELL} '/Users/thill/code/libredwg/build-aux/missing' makeinfo
checking MAKEINFO version... 
checking for doxygen... no
checking for jq... jq
checking JQ version... 1.6
checking for shellcheck... no
checking for rpmlint... no
checking for geojsonhint... no
checking for gjv... no
checking for jing... no
checking for valgrind... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating programs/Makefile
config.status: creating examples/Makefile
config.status: creating bindings/Makefile
config.status: creating bindings/python/Makefile
config.status: creating test/Makefile
config.status: creating test/xmlsuite/Makefile
config.status: creating test/unit-testing/Makefile
config.status: creating libredwg.pc
config.status: creating bindings/perl/Makefile.PL
config.status: creating programs/dwgfilter
config.status: creating programs/alive.test
config.status: creating programs/dxf.test
config.status: creating programs/json.test
config.status: creating programs/svg.test
config.status: creating logs-all.sh
config.status: creating log
config.status: creating dwg
config.status: creating dxf
config.status: creating json
config.status: creating svg
config.status: creating rw
config.status: creating dynapi_test_all.sh
config.status: creating unit_testing_all.sh
config.status: creating src/config.h
config.status: src/config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

**Comment by rurban** [comment]
There was a cast missing. thanks
