### ISSUE TITLE
Invalid json being generated

### ISSUE THREAD

**Issue by no-such-user** [LibreDWG/libredwg#397]
```
 % ./dwgread --format json ~/Downloads/architectural_-_annotation_scaling_and_multileaders.dwg | python -m json.tool

SUCCESS
Expecting , delimiter: line 66654 column 7 (char 1686274)
```

This file can be downloaded here: https://knowledge.autodesk.com/support/autocad-lt/downloads/caas/downloads/content/autocad-lt-2010-sample-files.html

I've seen this error on a couple of files.

**Comment by rurban** [comment]
Yes, ENDARRAY was missing on invalid FIELD.ChildValue and other JSON_END_REPEAT()
