### ISSUE TITLE
Placement of load_dwg.py

### ISSUE THREAD

**Issue by jengelh** [LibreDWG/libredwg#406]
It is uncommon for packages to directly put files into /usr/share; rather, they would place them in a subdirectory, e.g. /usr/share/libredwg.

```
examples/Makefile.in:dist_data_DATA = dwgadd.example load_dwg.py
examples/Makefile.am:dist_data_DATA = dwgadd.example load_dwg.py
```

These two lines probably should be dist_pkgdata_DATA=...

**Comment by rurban** [comment]
Yes, a bug. Thanks for the fix

**Comment by rurban** [comment]
should be fixed now
