### ISSUE TITLE
unknown_s[] fields in header

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#412]
in src/header.spec is section:
```
    for (i = 0; i < 3; i++) { // 3, 5, 205
      FIELD_RS (unknown_s[i], 0);
    }
```
Valid from AC1.50 to AC1009

I believe that this three values are numbers of ?, sections and header variables (idea, but i counted and seems that is).
On this values depends header variables (that's true).

3: ?
5: Number of sections (BLOCK, LAYER, STYLE, LTYPE, VIEW)
">=74 AND <=205": Number of header variables (from insertion_base, i don't know if 3d point is one or three)

In AC1.50 DWG files: 3, 5, 74; 3, 5, 83; 
In AC2.10 example (in [BLANK.DWG.gz](https://github.com/LibreDWG/libredwg/files/8088649/BLANK.DWG.gz)): 3, 5, 83
In AC1001 DWG files: 3, 5, 101
In AC1002 DWG files: 3, 5, 104; 3, 5, 114
In AC1003 DWG files: 3, 5, 120; 3, 5, 122
In AC1004 DWG files: 3, 5, 129
In AC1006 DWG files: 3, 5, 158; 3, 5, 160
In AC1009 DWG files: 3, 5, 204; 3, 5, 205

**Comment by michal-josef-spacek** [comment]
I found this idea with count of some now. When i am writing this issue :-D So i need to precise. Probably right (not count of bytes or something like this). I checked between 3,5,74 and 3,5,83 (header place in 3,5,83 is plus 0x01fa-0x02e4)

**Comment by rurban** [comment]
yes, looks convincing

**Comment by michal-josef-spacek** [comment]
@rurban Thanks for code, i will check it.

**Comment by michal-josef-spacek** [comment]
@rurban I checked AC1.50 and there is 74 variables in header, so idea is right. 3d point is three variables.
FYI: Last variable for AC1.50 is $DIMTAD.

**Comment by michal-josef-spacek** [comment]
@rurban We maybe need to count variables in header and stop parsing if count is greater than num_header_vars. 
We need to detect variables in header still. I have AC1.50, i will fill issues for it.

**Comment by rurban** [comment]
Yes, something like this. Still searching for my old parser ...

**Comment by michal-josef-spacek** [comment]
We could close this ticket. Third number is number of header variables definitively.

**Comment by rurban** [comment]
BTW: Found my old dwg11.c parser: https://gist.github.com/rurban/8c3a65ad8f75ff858c900392b7773dd0#file-dwg11-c

**Comment by michal-josef-spacek** [comment]
@rurban Great, thank you.
