### ISSUE TITLE
TEXTSTYLE in AC1.50 .. AC1009

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#414]
We have `unknown_12: 1 [RS 8]` actually and this is TEXTSTYLE index.
See AC2.10 examples:
* [BLANK.DWG.gz](https://github.com/LibreDWG/libredwg/files/8088649/BLANK.DWG.gz) `unknown_12: 0 [RS 8]` (default textstyle index)
* [TS1.DWG.gz](https://github.com/LibreDWG/libredwg/files/8096654/TS1.DWG.gz) `unknown_12: 1 [RS 8]` (FOO textstyle on index 1)
* [TS1.DXF.gz](https://github.com/LibreDWG/libredwg/files/8096658/TS1.DXF.gz) DXF output from r2.17

I don't know how to implement this change, because there is `BITCODE_H TEXTSTYLE;  /*!< code 5, DXF 7 */` in include/dwg.h

**Comment by rurban** [comment]
we need a TEXTSTYLE_r11 variant, same as for the other preR13 table indices.

**Comment by michal-josef-spacek** [comment]
@rurban Great, thank you
