### ISSUE TITLE
HAVE_ALLOCA_H and HAVE_LIBGEN_H symbols ignore results of cmake configure

### ISSUE THREAD

**Issue by carmethene** [LibreDWG/libredwg#420]
In cmakeconfig.h.in, it appears that the HAVE_ALLOCA_H and HAVE_LIBGEN_H symbols are hardcoded to 1, regardless of the results of the CHECK_INCLUDE_FILE() calls in CMakeLists.txt.  This causes compilation to fail under MinGW which does not provide the alloca.h header.

Changing:

#define HAVE_ALLOCA_H 1
#define HAVE_LIBGEN_H 1

To:

#cmakedefine HAVE_ALLOCA_H
#cmakedefine HAVE_LIBGEN_H

Resolves this issue.

**Comment by rurban** [comment]
Oops, thanks a lot
