### ISSUE TITLE
CMake build issue: MinGW does not support memmem()

### ISSUE THREAD

**Issue by carmethene** [LibreDWG/libredwg#422]
MinGW links the MSVC CRT rather than glibc, thus memmem() is not available.  It appears that an alternative is already provided in src/common.h, but this is never used when building through CMake as cmakeconfig.h.in #defines HAVE_MEMMEM as 1 in all cases.

CMake has a utility which easily resolves this issue:

In CMakeLists.txt:
```
include(CheckSymbolExists)
check_symbol_exists("memmem" "string.h" HAVE_MEMMEM)
```

In cmakeconfig.h.in:
```
/* Define if you have the `memmem' function. */
#cmakedefine HAVE_MEMMEM
```

**Comment by carmethene** [comment]
Just realised I'm adding to your workload, so I'll make a pull request :)

**Comment by rurban** [comment]
Nice, but beware the legal issues. Stay under 15 lines, or send a copyright assignment. Seems to be very fast now.
