### ISSUE TITLE
Disable logging a lot of info in console

### ISSUE THREAD

**Issue by GeorgGrebenyuk** [LibreDWG/libredwg#424]
Hi, i have a little question - how disable logging info in console? I have reading [that post](https://github.com/LibreDWG/libredwg/issues/25#issuecomment-399935076), but couldn't understood what need did. I work in MS VS's environmental*
![image](https://user-images.githubusercontent.com/55656376/156940777-bd3bd241-f27a-4325-bd2f-74f8054099ee.png)
P.S. Or may be with variable "DWG_LOGLEVEL" ... how it use?
`#define 	DWG_LOGLEVEL   DWG_LOGLEVEL_ERROR` not working ... log there is anyway

**Comment by carmethene** [comment]
Dwg_Data has a member which controls the log level.  If you don't initialize that struct, it'll get some random value which will likely enable all the debug logging.  Simple fix:

`memset(&my_dwg, 0, sizeof(Dwg_Data));
`

**Comment by GeorgGrebenyuk** [comment]
> memset(&my_dwg, 0, sizeof(Dwg_Data));

Yeah, thank you -- it's variable that I wanted find! (it was placed more deeper that I thought 😅)
