### ISSUE TITLE
dwg2SVG

### ISSUE THREAD

**Issue by Takieddinex** [LibreDWG/libredwg#429]
Hello,
I would like to use the library already compiled in Windows but when I enter the command dwg2SVG it returns empty svg output

Could you help me please? 
![image](https://user-images.githubusercontent.com/95845810/161934759-34cbe610-c479-4018-b96d-b03fa72f592f.png)
![image](https://user-images.githubusercontent.com/95845810/161934843-5d6ffb72-21f0-4e1f-87c6-b99718b8628f.png)
![image](https://user-images.githubusercontent.com/95845810/161934918-1c394503-f560-4b9e-abe4-919723dbc903.png)

**Comment by rurban** [comment]
pasting Images does not really help.
you need to leave out the [] part, this means optional. verbosity 0- 9.

**Comment by rurban** [comment]
inspect the bet.svg for any errors.
or use -v3

**Comment by Takieddinex** [comment]
"This XML file does not appear to have any style information associated with it. The document tree is shown below."

I'm doing the inspection but I only find this message in span 
I tried -v3 but it doesn't work

**Comment by Takieddinex** [comment]
Hello ! 
I can't find the method to do the conversion if you can please help me 

./dwg2SVG.exe [-v[0-9]] D:/libredwg/projet.dwg>D:/libredwg/test.svg

this is the command I enter and I would get an empty svg file as output 

![image](https://user-images.githubusercontent.com/95845810/164033197-0526cb19-3022-498e-b300-932318978bb3.png)

Thank you !!
