### ISSUE TITLE
AC402b magic string

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#436]
This magic AC402b string isn't R1.4 version. 
See links:
https://www.cadforum.cz/en/qaID.asp?tip=868
http://devel.gvsig.org/sites/org.gvsig.dwg/2.0-SNAPSHOT/gvsig-base-library-pom/org.gvsig.dwg/xref/org/gvsig/dwg/lib/DwgFile.html

**Comment by rurban** [comment]
The 2nd link looks very good.
And we need to separate unreleased alpha/beta versions, and post-release bugfix versions (such as r13c3)

**Comment by rurban** [comment]
Reworking the versions now
