### ISSUE TITLE
Printing of flags

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#469]
Hi @rurban,

You are creating nice flags printing (https://github.com/LibreDWG/libredwg/commit/4a52199ea72b9a47ff21abc14f8b2485fdd101cd)
Could we add this kind of logging to all flags?

**Comment by michal-josef-spacek** [comment]
Example output:
```
flag_r11: 0x60 [RC 0]
          HANDLING (20) PSPACE (40)
```

**Comment by michal-josef-spacek** [comment]
I created https://github.com/LibreDWG/libredwg/pull/546

**Comment by rurban** [comment]
Think we are done here on the most basic entities
