### ISSUE TITLE
copyright assignment denis

### ISSUE THREAD

**Issue by rurban** [LibreDWG/libredwg#47]
http://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob_plain;f=doc/Copyright/request-assign.future;hb=HEAD

**Comment by DenisPryt** [comment]
I sent the letter three days ago
![image](https://user-images.githubusercontent.com/11017991/48997050-9479d680-f15f-11e8-8466-7c7b3f768d36.png)

**Comment by rurban** [comment]
Great. This will need 1-2 weeks to process. no worries, we got time.

**Comment by DenisPryt** [comment]
I have received a letter. I will sign it within a couple of days

**Comment by rurban** [comment]
Assignment confirmed
