### ISSUE TITLE
How to use libredwg in Visual Studio?

### ISSUE THREAD

**Issue by ztkboj58623** [LibreDWG/libredwg#496]
I download the libredwg-0.12.5-win32.zip,then I find the lib is libredwg.dll.a.In general, the file format in visual studio is .lib
Is there an example of using libredwg in Visual Studio？

**Comment by rurban** [comment]
No, you need a C99 compliant C compiler, and Visual Studio is not one.
https://stackoverflow.com/questions/48615184/does-visual-studio-2017-fully-support-c99

Adding msvc support is not a priority, since there exist free C compilers which are first free and 2nd better.
