### ISSUE TITLE
_dwg_object_LAYER.plotflag always 0

### ISSUE THREAD

**Issue by zamtmn** [LibreDWG/libredwg#509]
I'm trying to import dwg, but I'm losing information about printing layers

**Comment by zamtmn** [comment]
[printflag.zip](https://github.com/LibreDWG/libredwg/files/9220067/printflag.zip)
test files 2000-2018

**Comment by rurban** [comment]
Right, I had it wrong.

plotflag is the 5th bit of the LAYER.flag.
The layer on_unlock_print has it set (flag 1012 or 0x3f4),
the others have it not set. (flag 1006 or 0x3f0)

**Comment by zamtmn** [comment]
Now it work. Thanks!
