### ISSUE TITLE
Wrong layers properties after dxf loading

### ISSUE THREAD

**Issue by zamtmn** [LibreDWG/libredwg#510]
if I try load dxf different versions, I get 0 for on, locked, plotflag for all layer 
[layersdxf.zip](https://github.com/LibreDWG/libredwg/files/9228210/layersdxf.zip)

**Comment by rurban** [comment]
Yes, it is completely wrong. I need to seperate the DXF 70 flag, from the internal DWG bitmask (I'll call it flag0)
