### ISSUE TITLE
Some invalid DXF files were created

### ISSUE THREAD

**Issue by cbvgn** [LibreDWG/libredwg#516]
File 222.dxf has a root dictionary, but not as the first entity in the OBJECTS section as required
File A2.dxf has an invalid empty line at line number 18395 and 18498, after fixing that same issue as in file 222.dxf
[invalid files.zip](https://github.com/LibreDWG/libredwg/files/9257875/invalid.files.zip)

**Comment by rurban** [comment]
Oops, duplicate with #536. Sorry, handled there
