### ISSUE TITLE
Assertion failed in binary dwglayers

### ISSUE THREAD

**Issue by Yhcrown** [LibreDWG/libredwg#519]
Hi, developers of libredwg:
I also find an assertion failed in binay **dwglayers**. The input and the information are as follows. Any help would be greatly appreciated from you :D
**input:**
https://github.com/Yhcrown/fuzzing-crashes/blob/main/validated/dwglayers/0
**output:**
```
dwglayers: dwglayers.c:166: int main(int, char **): Assertion `_ctrl->entries[i]' failed.
```
**enviroment:**
Ubuntu 22.04 LTS
Linux lab-pro 4.15.0-147-generic
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Ubuntu clang version 14.0.6

**Thanks & Best regards !**

**Comment by rurban** [comment]
Invalid input, caused by fuzzing obviously.
The link isr3sd, so I cannot check it

**Comment by Yhcrown** [comment]
> Invalid input, caused by fuzzing obviously.
> The link is dead, so I cannot check it

Sorry, I've updated.

**Comment by michal-josef-spacek** [comment]
FYI: Autocad R14 cannot open this file.
