### ISSUE TITLE
dwg2dxf fails

### ISSUE THREAD

**Issue by turtle0x1** [LibreDWG/libredwg#52]
When running the command `dwg2dxf test.dwg` on the .dwg sent to @rurban you get the following output

```
Warning: Object handle not found, 80 in 11073 objects
Warning: Object handle not found, 208 in 11073 objects
Warning: Object handle not found, 208 in 11073 objects
Warning: Object handle not found, 82 in 11073 objects
Writing DXF file test.dxf
Segmentation fault (core dumped)
```

When opening the resulting dxf in librecad it recognises some of the layers but no lines or any other drawing elements

**Comment by rurban** [comment]
empty paper_space in
`hdr = _ctrl->paper_space->obj` dxf_blocks_write()
