### ISSUE TITLE
missing arcsplit, wrong null json value in geojson

### ISSUE THREAD

**Issue by mahmoudadel54** [LibreDWG/libredwg#520]
I have a dwg with drawing arcs. I tried to use dwgread.exe with GeoJSON output, it gives me null in geometry

![image](https://user-images.githubusercontent.com/58145645/195377116-225549e9-5352-4249-8bd2-03a0391c2898.png)

Please If someone can help !!

**note: I tried different dwg versions: AutoCad 2010, 2019 and same results

**Comment by rurban** [comment]
See out_geojson.c:775
```
      // needs explosion of arc into lines
      // dwg_geojson_ARC(dat, obj);
      LOG_TRACE ("ARC not yet supported")
```

**Comment by mahmoudadel54** [comment]
> See out_geojson.c:775
> 
> ```
>       // needs explosion of arc into lines
>       // dwg_geojson_ARC(dat, obj);
>       LOG_TRACE ("ARC not yet supported")
> ```

Actually I have no experience with C language

**Comment by rurban** [comment]
I started working on it in the work/arcsplit branch
