### ISSUE TITLE
Issue with reading of numheader_vars

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#540]
Commit d6029e974 with changes in dwg_add_Document() is bad.

Decoding process is:
* read numheader_vars from DWG file
* dwg_add_Document (which after this commit set this variable to different values)
* usage of numheader_vars

As I understand, we need to move this setting to dwg_new_Document()

**Comment by rurban** [comment]
Looks like so, indeed.. Maybe just set it there if it's empty

**Comment by michal-josef-spacek** [comment]
I believe that isn't empty.

**Comment by michal-josef-spacek** [comment]
Example which is not working
[3DFACE1.DWG.gz](https://github.com/LibreDWG/libredwg/files/10253686/3DFACE1.DWG.gz)

**Comment by rurban** [comment]
I see the problem now. decode_r11 needs to call add_Document because of all the tables, but we must not ignore the existing numheader_vars. Unless we change the target version.

**Comment by michal-josef-spacek** [comment]
It's working, thanks.
