### ISSUE TITLE
ERROR: Invalid LTYPE.dash x 61

### ISSUE THREAD

**Issue by turtle0x1** [LibreDWG/libredwg#55]
When running over some dwgs from the same project I get the errors

```
Warning: Invalid handleref: wanted code 4, got (1.7.0)
ERROR: Invalid LTYPE.dash x 61

ERROR: Invalid LTYPE.dash x 215

ERROR: num_inserts [RC 0]: 136!

Warning: Invalid handleref: wanted code 4, got (1.7.0)
ERROR: Invalid LTYPE.dash x 61

ERROR: Invalid LTYPE.dash x 215
```

**Comment by rurban** [comment]
This should have been fixed with ca05a711d94f746dabd7f96c155dbfb58c3de280
Is it not?

**Comment by turtle0x1** [comment]
Nope just recompiled master (although i was on the smoke branch) and it doesn't work with at least one of the .dwg want a copy ?

**Comment by rurban** [comment]
yes, please

**Comment by rurban** [comment]
Will eventually fix later. For now its too harmless
