### ISSUE TITLE
supported .dwg format versions?

### ISSUE THREAD

**Issue by abubelinha** [LibreDWG/libredwg#584]
Not a bug, but a question.
I am not a CAD user, and I don't have Autocad. But I've got some .dwg files that I need to read/convert to some other readable format. 
I tested a few free online readers/converters but looks like they are made for older .dwg versions. 

I guess my files are just the default Autocad 2022 .dwg output format since I was told they were produced with that version.
Is libredwg supposed to handle that, or is it limited to older versions too? 

Thanks and sorry about the newbie question.

**Comment by fmunozs** [comment]
Hello, 

According to [1] Autocad 2022 should use 2018 format and I see some included examples on the test data with that version, so I guess its supported.

My recommendation is to compile and test it! there is an utility called dwg2svg included on libredwg that could help, if it doesnt work you could share some sample files to this project.

Also, have you tried importing them on librecad? it uses a different lib for reading DWG, not sure about the support. 

Regards

[1] https://knowledge.autodesk.com/support/autocad/learn-explore/caas/sfdcarticles/sfdcarticles/AutoCAD-drawing-file-format.html

**Comment by rurban** [comment]
LibreDWG can read all DWG format versions, also 2022. If not, I'd like an example

**Comment by abubelinha** [comment]
> You can use the Discussion to get this kind of help! https://github.com/LibreDWG/libredwg/discussions

Sorry, I wasn't aware of that. Good to know, thanks!

> LibreDWG can read all DWG format versions, also 2022. If not, I'd like an example

Great. I'll try LibreDWG to see if it works. 
As it's a private map I can't post those files here: how can I share them privately @rurban ?

Anyway, as @fmunozs suggests I posted a couple of questions in Discussion https://github.com/LibreDWG/libredwg/discussions/585
Thank you both for your help.

**Comment by rurban** [comment]
private sharing is ok, sure.
