### ISSUE TITLE
Fix HANDSEED in preR13

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#596]
Example:
[HS1.DXF.gz](https://github.com/LibreDWG/libredwg/files/10474512/HS1.DXF.gz)
[HS1.DWG.gz](https://github.com/LibreDWG/libredwg/files/10474513/HS1.DWG.gz)

Actual output:
```
HANDLING: 1 [RS 70]
HANDSEED: 0 [RSx 5]
unknown_4f2: 4080275968 [RL 70]
```

In DXF is: 
```
$HANDLING
 70
     1
  9
$HANDSEED
  5
1234F4
  9
```

**Comment by michal-josef-spacek** [comment]
Could i do something like https://github.com/LibreDWG/libredwg/pull/597 ?
Output:
```
HANDLING: 1 [RS 70]
HANDSEED: 0.8.1234F3 [H 5]
```

**Comment by rurban** [comment]
Not with big endian, otherwise better than before
