### ISSUE TITLE
Identify second part of $MENU header variable

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#626]
Example:
[MENU1.DXF.gz](https://github.com/LibreDWG/libredwg/files/10567704/MENU1.DXF.gz)
[MENU1.DWG.gz](https://github.com/LibreDWG/libredwg/files/10567705/MENU1.DWG.gz)

In example is longest menu path, which could be.
```C:\ABCDEFG\HIJKLMNO\PQRSTUVW\XYZABCDE\FGHIJKLM\NOPQRS\ACAD```

First part is existing menu.
Second part is unknown_46 - 45 characters + null string

**Comment by michal-josef-spacek** [comment]
thanks @leshasoft in https://github.com/michal-josef-spacek/CAD-Format-DWG-AC1009/issues/1

**Comment by rurban** [comment]
Maybe name it MENUPATH

**Comment by rurban** [comment]
They call it internally MENUNAME, but I haven't found the old code with the merge yet
