### ISSUE TITLE
dwgadd: Fix attdef and attrib tag for releases which could use utf8

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#628]
attdef and atrib tag is one word and R13 (tested on R14) supports utf8 string for it.
dwgadd don't encode utf8 string in case of tag actually.

**Comment by rurban** [comment]
Fixed by f6db2bd4a65317348dddbc56e313079063a36c08 ?

**Comment by michal-josef-spacek** [comment]
> Fixed by [f6db2bd](https://github.com/LibreDWG/libredwg/commit/f6db2bd4a65317348dddbc56e313079063a36c08) ?

No. There is FMT_TBL for tag and this don't support utf8

**Comment by michal-josef-spacek** [comment]
btw: I don't know how about encodings in preR13 :-D

**Comment by rurban** [comment]
The preR13 encodings are single-byte system-specific, but our dwg_add API accepts utf-8 only and converts its to the used encoding.

**Comment by michal-josef-spacek** [comment]
I don't think that could be FMT_ANY, tag could be only one word

**Comment by rurban** [comment]
So I actuallly did read the docs now. You are right. They are special.

**Comment by rurban** [comment]
Fixed
