### ISSUE TITLE
dwgfilter: XPath-like query expr

### ISSUE THREAD

**Issue by rurban** [LibreDWG/libredwg#64]
In principle like [osmfilter](https://wiki.openstreetmap.org/wiki/Osmfilter), but with a sane query expression language.
Something like XPath or JSONPath with the dot. notation seem to be the best fit.

 *  The query expression should look a bit like https://istio.io/docs/reference/config/policy-and-telemetry/expression-language/
 *  XPath supports trees, we only have lists, so `/` or `//` is unneeded.
 *  JSONPath uses the nicer dot syntax for fields, but is a bit too limited.
 *  Implementing a query language (parser, bytecode, vm) seems to be overkill, so rather just pass it through jq (https://stedolan.github.io/jq/manual/v1.6/) as json. This way dwgfilter can even be a simple shell script.

By default pure, only display the result of the filter query.
It also needs to handle destructive changes: --delete and --keep for simple boolean queries
and maybe also changes (renames, transform) by assignment ops (+=) or s///.

depends on: #59

**Comment by turtle0x1** [comment]
Was this released in 0.8 ?

**Comment by rurban** [comment]
Nope, sorry
I just released the latest updates, because I'm busy with something else and it will need a few months until the next update.

**Comment by turtle0x1** [comment]
Hi @rurban been a while, I still very much need the functionality but am getting build errors when trying to build from https://github.com/LibreDWG/libredwg/commit/24695ce04c43403a152c8899e222157d1d7061a3 any updates or anything I can do to help ?

**Comment by rurban** [comment]
The current plan is to use jq as filter with json out | jq | json in.
What's missing is the json importer on which I will start working soon. I already finished the much harder dxf importer, so json will be much easier.

**Comment by turtle0x1** [comment]
Hi ruban, 

I have managed to modify the program to get it "working" but the output isn't particularly clear to me (maybe my modifications have broken things) 

First i have disabled the functions 
```
match_MLINESTYLE
match_LAYER_INDEX
match_ACDBNAVISWORKSMODELDEF
```
Then removed their usage  
```
   ...
   else if (obj->type == //the type)
   ...
```
Then renamed these old functions
```
get_first_owned_object -> get_first_owned_entity
get_next_owned_object -> get_next_owned_object
```
Now when I run the program against (test2.dwg) which i previously sent you

like so `./dwgfilter -i 'BLOCK_HEADER.xref_pname' /home/a/libredwg/dantest/test2.dwg` I get no output

When I run the command `./dwgfilter '19' /home/a/libredwg/dantest/test2.dwg`
I get the output 
```
/home/a/libredwg/dantest/test2.dwg MTEXT 1: 1905
/home/a/libredwg/dantest/test2.dwg MTEXT 1: 1195
/home/a/libredwg/dantest/test2.dwg MTEXT 1: 1930
/home/a/libredwg/dantest/test2.dwg BLOCK_HEADER 1: REDACTED_PATH_TO_XREF
/home/a/libredwg/dantest/test2.dwg MTEXT 1: 1985
/home/a/libredwg/dantest/test2.dwg MTEXT 1: 1915
/home/a/libredwg/dantest/test2.dwg MTEXT 1: 1905
/home/a/libredwg/dantest/test2.dwg MTEXT 1: 2190
/home/a/libredwg/dantest/test2.dwg MTEXT 1: 2.191
/home/a/libredwg/dantest/test2.dwg MTEXT 1: SOME_REDACTED_FILE_NAME
```
Now '19' is a line entity according to `dwg.h` so im confused as to why its finding lots of MTEXT ? 

Thanks
Dan

**Comment by turtle0x1** [comment]
Ill take a look as your most recent commit when i get home, your commit style is abit odd so its difficult to really see whats changed

**Comment by turtle0x1** [comment]
@rurban  still getting tons of build errors on this new version

**Comment by turtle0x1** [comment]
d0b9def - yay no build errors :smile: 

It still doesn't quite work as described: 
> Now when I run the program against (test2.dwg) which i previously sent you
> 
> like so ./dwgfilter -i 'BLOCK_HEADER.xref_pname' /home/a/libredwg/dantest/test2.dwg I get no output
> 
> When I run the command ./dwgfilter '19' /home/a/libredwg/dantest/test2.dwg
> I get the output
> 
> /home/a/libredwg/dantest/test2.dwg MTEXT 1: 1905
> /home/a/libredwg/dantest/test2.dwg MTEXT 1: 1195
> /home/a/libredwg/dantest/test2.dwg MTEXT 1: 1930
> /home/a/libredwg/dantest/test2.dwg BLOCK_HEADER 1: REDACTED_PATH_TO_XREF
> /home/a/libredwg/dantest/test2.dwg MTEXT 1: 1985
> /home/a/libredwg/dantest/test2.dwg MTEXT 1: 1915
> /home/a/libredwg/dantest/test2.dwg MTEXT 1: 1905
> /home/a/libredwg/dantest/test2.dwg MTEXT 1: 2190
> /home/a/libredwg/dantest/test2.dwg MTEXT 1: 2.191
> /home/a/libredwg/dantest/test2.dwg MTEXT 1: SOME_REDACTED_FILE_NAME
> 
> Now '19' is a line entity according to dwg.h so im confused as to why its finding lots of MTEXT and an XREF path ?

**Comment by turtle0x1** [comment]
@rurban still semi frequently building this, it still doesn't quite work as expected in-regards to extracting xref names im using the command `dwgfilter 'BLOCK_HEADER.xref_pname' DWG_PATH` but it returns nothing

doing something silly like `dwgfilter '1' DWG_PATH` returns lots of items, some of which are xref paths which start with `BLOCK_HEADER 1:`, if there is anything I can do to help (development (if you can point me in the right direction) or more drawings) I would be happy todo so!

**Comment by rurban** [comment]
the current filter branch just has grep. the new filter will work via out json, jq, in json.
Just working on that now. It's getting closer on r2000, just tables and fields are broken still.

**Comment by turtle0x1** [comment]
Can you hint at how id get xref names ? Thanks again 😊

**Comment by turtle0x1** [comment]
@rurban this produces invalid json that python cant read, trailing values like  `"value": 3.` aren't valid

**Comment by rurban** [comment]
> @rurban this produces invalid json that python cant read, trailing values like `"value": 3.` aren't valid

Still working on json...

**Comment by turtle0x1** [comment]
@rurban my coding skills in C are 0, For me it comes from the `"type": 69` "DIMSTYLE" - thats the only errors in my json so far - I spent a few hours trying to fix it but I give up!

**Comment by rurban** [comment]
DIMSTYLE type was broken indeed. Fixed with c21b6fff3f856f36c4938b6eec6f1d4bdabb8660

**Comment by turtle0x1** [comment]
@rurban that didn't fix it :disappointed:

**Comment by rurban** [comment]
Then I'd love to get that DWG

**Comment by turtle0x1** [comment]
@rurban whats your email ?
