### ISSUE TITLE
Crash during DWG read

### ISSUE THREAD

**Issue by timoria21** [LibreDWG/libredwg#657]
Hello,

This DWG file generates a 0x941 error during reading.

[error_0x941.zip](https://github.com/LibreDWG/libredwg/files/10941272/error_0x941.zip)

**Comment by timoria21** [comment]
Sure, here is the output. The same is true for TrueView.

![image](https://user-images.githubusercontent.com/79898585/224973829-1e6e32dc-ebc9-4d26-8233-ec57e4c62a43.png)

**Comment by rurban** [comment]
Cannot repro any crash, also not with asan

**Comment by michal-josef-spacek** [comment]
> Cannot repro any crash, also not with asan nor valgrind. SUCCESS 0x45

Same for me. SUCCESS 0x45
