### ISSUE TITLE
LWPolyline closed flag

### ISSUE THREAD

**Issue by gentilinigian** [LibreDWG/libredwg#658]
Hello,

Please consider the attached file 2.dwg.

There is an LWPolyline entity with handle **1019** that should be closed.

By looking at the [dxf group codes docs](http://docs.autodesk.com/ACD/2011/ENU/filesDXF/WS1a9193826455f5ff18cb41610ec0a2e719-79fc.htm) I see that the closed flag value of a LWPolyline is 1 (bit-coded), and the other possible flag values are 0 and 128.

But looking at the json file the flag value is 528, 001000010000. See below.

![image](https://user-images.githubusercontent.com/38076337/224365865-a72605ce-a9b7-4912-b22d-ed9338041517.png)

I am aware that this is not a dxf file and that the flag value might differ, but the [OpenDesign Specification](https://www.opendesign.com/files/guestdownloads/OpenDesign_Specification_for_.dwg_files.pdf) is not helping much.

I did a few tests and the 512 bit seems to be the right flag value for a closed LWPolyline in this case, is this ok? Should I just keep that as the right value or am I missing something?

Thank you.

[2.zip](https://github.com/LibreDWG/libredwg/files/10943763/2.zip)

**Comment by michal-josef-spacek** [comment]
In actual version is (```dwgread -v9 2.dwg```):
```
Object number: 338/152, Size: 452 [MS], Type: 77 [BS], Address: 21579
Add entity LWPOLYLINE [338] Decode entity LWPOLYLINE
bitsize: 3598 [RL] @3.2
 Hdlsize: 18, hdl_dat: @449.6 - @452.0 (452)
handle: 0.2.3FB [H 5]
EED[0] size: 0 [BS] (end)
num_eed: 0
preview_exists: 0 [B 0]
entmode: 2 [BB 0]
num_reactors: 0 [BL 0]
is_xdic_missing: 1 [B 0]
color.raw: 0x100 [BSx 0]
ltype_scale: 1.000000 [BD 48]
ltype_flags: 0 [BB 0]
plotstyle_flags: 0 [BB 0]
invisible: 0 [BS 60]
linewt: 0x1d [RC 370]
layer: (5.1.2E) abs:2E [H 8] => LAYER LGP
--common_size: 82
flag: 528 [BS 70]
      HAS_NUM_BULGES(0x10) CLOSED(0x200)
num_points: 24 [BL 90]
num_bulges: 24 [BL 0]
...
```

**Comment by rurban** [comment]
As you in the log output (thanks to Michal) you see the value of the closed bit in the flags. 0x200 or 512 indeed.
Also  https://github.com/LibreDWG/libredwg/blob/3edf9479afc1dc12deaa8f44ac73c4cde655a2f6/include/dwg.h#L8333

**Comment by gentilinigian** [comment]
Thank you, it is very clear now. I didn't see it.
