### ISSUE TITLE
How to read OrdinateDim text position

### ISSUE THREAD

**Issue by gentilinigian** [LibreDWG/libredwg#660]
Hello,

I have a question,
I'm trying to read an OrdinateDim entity _(attached file OrdinateDim.zip)_ but it's not very clear to me how to get the final text position.

Please take a look at the image below:
![image](https://user-images.githubusercontent.com/38076337/224994049-a84905c9-4b59-46fc-ba70-f13167551f95.png)

Do you have any suggestions on how to get from the text position values in the json file (243.75, -79.66) to the ones that I should see when I render the entity (84.47, 243.74) ?

Thank you

[OrdinateDim.zip](https://github.com/LibreDWG/libredwg/files/10967956/OrdinateDim.zip)

**Comment by michal-josef-spacek** [comment]
@gentilinigian If you could send DXF from AutoCAD too, it will be great.

Seem as bug.
