### ISSUE TITLE
ERROR: bit_read_UMC: error parsing modular char, i=-1,j=42,result=0x1112e4a7652

### ISSUE THREAD

**Issue by timoria21** [LibreDWG/libredwg#662]
Hello,

Please consider the attached file [test.zip](https://github.com/LibreDWG/libredwg/files/10999915/test.zip) 

First, I tried to read a DWG file using dwgread.exe with the following command (powershell):
`.\libredwg-0.12.5-win64\dwgread.exe -o .\PressEdited.json .\PressEdited.dwg`
This successfully generated a .json file.

Then, I tried to write the .json content again into a DWG file with the following command:
`.\libredwg-0.12.5-win64\dwgwrite.exe -o .\PressTest.dwg .\PressEdited.json 2>&1 > outputEdited.txt`
This generates a lot of **errors** and **doesn't write any DWG file**.
You can find the output inside the file: outputEdited.txt.
The file doesn't seem to be corrupted as I can view/save it using AUTOCAD2007.

Is it a bug or a corrupted file?
If it's a corrupted file, is it possible to fix these errors myself (without changing the dwg version)?

Thanks,

Dave

**Comment by michal-josef-spacek** [comment]
The first issue is decoding of PressEdited.dwg. There are many errors which created blank entity {} in JSON file.

@timoria21 In each issue it's the best to add DXF file from same version of AutoCAD.

**Comment by rurban** [comment]
reading the dwg:

ERROR: bit_read_UMC: error parsing modular char, i=-1,j=42,result=0x1112e4a7652
Warning: handleoff 0 looks wrong, max_handles 58130 - last_handle 3855443169666 = 18446740218266440080 (@8
54699)
Warning: offset 1 looks wrong, should be prevsize 74

Next object: 12912 Handleoff: 0 [UMC] Offset: 1 [MC]
==========================================
Object number: 12912/3270, Size: 17408 [MS], Type: 202 [BS], Address: 754319
ERROR: Invalid object type 202, only 8 classes
ERROR: Invalid class index -298 < 0

**Comment by rurban** [comment]
libdxfrw fails with the same UMC reading bug on handleoffset \xd2\xec\xa9\xf2\x92\xa2
oda and acad work ok

**Comment by rurban** [comment]
Fixed
