### ISSUE TITLE
DIMMALTZ and DIMALTZ need to be merged

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#672]
There are DIMMALTZ and DIMALTZ variables in the header and the DIMSTYLE object.
These values are the same, the conversion of AC1012 DIMALTZ = 1 to DXF is bad (0).

**Comment by michal-josef-spacek** [comment]
I prepared https://github.com/LibreDWG/libredwg/pull/673

**Comment by michal-josef-spacek** [comment]
Same for DIMMALTTZ and DIMALTTZ

**Comment by rurban** [comment]
Done
