### ISSUE TITLE
No num_dashes writes to JSON in preR13

### ISSUE THREAD

**Issue by leshasoft** [LibreDWG/libredwg#690]
In the LTYPE section, num_dashes is not written, although it should be according to the code.

```
              FIELD_TFv (description, 48, 3);
              FIELD_RC (alignment, 72);
              FIELD_RCu (num_dashes, 73);
              FIELD_RD (pattern_len, 40);
              FIELD_VECTOR (dashes_r11, RD, num_dashes, 49);
              ENDRECORD ();
```

https://github.com/LibreDWG/libredwg/blob/master/src/out_json.c#L2055

**Comment by rurban** [comment]
Not a bug, this is by design.
JSON arrays don't need an extra size, the size of the dashes_r11 is num_dashes.

All num_* json vars are treated like this.
