### ISSUE TITLE
dwgread infinite loop in DWG file generated by libredwg

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#715]
There is an infinite loop in the dwgread on file which I generated by the libredwg.

File:
[test.dwg.gz](https://github.com/LibreDWG/libredwg/files/11341524/test.dwg.gz)

**Comment by rurban** [comment]
Yes, had the same

**Comment by rurban** [comment]
mesh vertex support seems to be missing still. it would be nice to get the json, scr, add or original dwg for this.

**Comment by michal-josef-spacek** [comment]
@rurban I don't know which one was. 

Main point of this ticket was infinite loop, but I understand, it's related to bad parsing.

Issue with polylines is described in https://github.com/LibreDWG/libredwg/issues/71

**Comment by michal-josef-spacek** [comment]
In [0.12.5.5504](https://github.com/LibreDWG/libredwg/releases/tag/0.12.5.5504) is still present on my instalation. 

We can move to https://github.com/LibreDWG/libredwg/issues/713 and fix this issue, it's probably related.
