### ISSUE TITLE
error code 68

### ISSUE THREAD

**Issue by berry0511** [LibreDWG/libredwg#729]
src file:  [huafei.zip](https://github.com/LibreDWG/libredwg/files/11514535/huafei.zip)

code:
    auto dwg_ = new Dwg_Data;
    int success;
    dwg_->num_objects = 0;
    success = dwg_read_file(file_path_.string().c_str(), dwg_);

return val:
    success = 68
dwg_errstrings shows: UNHANDLEDCLASS VALUEOUTOFBOUNDS 

version: latest master

**Comment by berry0511** [comment]
further more:
using dwgread try to open the file shows:
![image](https://github.com/LibreDWG/libredwg/assets/16091368/5b6b6cfc-d353-4ce9-a56d-8d86b28bdac4)

**Comment by rurban** [comment]
Yes, and?
We cannot read all classes and never will without the accompaning ARX sources

**Comment by berry0511** [comment]
> 



> Yes, and? We cannot read all classes and never will without the accompaning ARX sources

what is the ARX sources?

**Comment by rurban** [comment]
Peiwen Geng ***@***.***> schrieb am Fr., 19. Mai 2023, 19:33:

> Yes, and? We cannot read all classes and never will without the
> accompaning ARX sources
>
> what is the ARX sources?
>
DWG allows external dynamic objects, which are compiled to ARX. Many
companies build their own objects with ARX, and they dont give away how
their objects are stored.

**Comment by rurban** [comment]
More worrying is 

Warning: checksum: 0x3008130e (calculated) mismatch
Warning: Invalid sections: 0 != numgaps: 0 + numsections: 189
