### ISSUE TITLE
`out_json.c` produces incomplete entity information

### ISSUE THREAD

**Issue by nick-bull** [LibreDWG/libredwg#73]
Certain entities, e.g., `LINE`, don't have all of their relevant properties mapped, e.g., `start`, `end` into json: 

    {
      "entity": "LINE",
      "type": 19,
      "size": 60,
      "bitsize": 443,
      "picture_exists": 0,
      "thickness": 0.000000,
      "extrusion.x": 0.000000,
      "extrusion.y": 0.000000,
      "extrusion.z": 1.000000    
    }

Any ideas how to extend the data? I can't work out how to.

**Comment by nick-bull** [comment]
Another argument with some malformed outputs (note `edge_obscured_color.name`):

    {
      "object": "VISUALSTYLE",
      "type": 506,
      "size": 169,
      "bitsize": 1282,
      "desc": "OverhangOff",
      "type": 21,
      ...
      "edge_obscured_color": 0,
      "edge_obscured_color".rgb: 0000cc,
      "edge_obscured_color.name": "@0	 	A§èG÷`ÈPÚl¢8",
      "edge_obscured_color.bookname": "(null)",
      "parenthandle": "HANDLE(4.1.40) absolute:40",
      "reactors":      [
        "reactors": "HANDLE(4.1.40) absolute:40"
      ],
      "xdicobjhandle": "HANDLE(3.3.94850) absolute:94850"
    },

**Comment by rurban** [comment]
With d8dfa350e00baf619e54a33d2f63be0155374065 (smoke/json) the json output is now fixed
