### ISSUE TITLE
api: add dwg_obj_layer_set_name

### ISSUE THREAD

**Issue by nick-bull** [LibreDWG/libredwg#74]
There's a `dwg_obj_layer_get_name`, how about the ability to `set` it too. I understand entities and layers both have a `layer_name` property, does that complicate things? How about tables?

**Comment by rurban** [comment]
Sure, that's needed. All common_entity fields should be set'able for the writer.
But completing the writer is low priority, first we'll fix the reader issues.

**Comment by rurban** [comment]
Check all layer table entries for a matching name, keep the handle.
Set the object layer handle to this handle.

**Comment by rurban** [comment]
See in_dxf.c how do do that. `dwg_find_tablehandle` (by name)
