### ISSUE TITLE
Wrong conversion to JSON for MENU header variable

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#756]
Example: 
[BLANK.DWG.gz](https://github.com/LibreDWG/libredwg/files/11677294/BLANK.DWG.gz)

Convert to JSON:
```dwgread -o BLANK.json BLANK.DWG```

In JSON is:
```
...
"MENU": "acad\u0000e\u0000g\offic\u0000",
...
```

Conversion back:
```dwgwrite BLANK.json```
returns:
```
ERROR: Invalid json. jsmn error at pos: 1608 (...   "MENU": "acad\u000 ...)
ERROR 0x800
```

Probably missing escape for ```\```

**Comment by michal-josef-spacek** [comment]
Second bug is that in JSON should be ```"MENU": "acad"

**Comment by rurban** [comment]
"acad\u0000e\u0000g\offic\u0000" Invalid \o

**Comment by michal-josef-spacek** [comment]
@rurban Escaping is ok, thanks

There is an issue with the end of the string defined by ```\0``` still.
In DWG file is ```acad``` but json contain trailing characters after ```\0``` like ```acad\u0000e\u0000g\\offic\u0000```

**Comment by rurban** [comment]
Yes, that's on purpose. If the slack. Is not clean, we keep it

**Comment by michal-josef-spacek** [comment]
But why?

**Comment by rurban** [comment]
Well, I wanted to keep it bit-compat to get the very same CRC  values also, so that diff's are not that cluttered. It doesn't work with floating point values, but the rest is now equal. See json-check

**Comment by michal-josef-spacek** [comment]
Ah, ok. Good point.

Maybe could be better to have "menu": "acad" and "menu_raw": "acad\u0000g...........".
Actual concept is not much intuitive.

**Comment by rurban** [comment]
Hmm, that is for every fixed string, preR13. too much work

**Comment by michal-josef-spacek** [comment]
I understand. Or array with value and raw value.
