### ISSUE TITLE
convert failed in dwg2dxf

### ISSUE THREAD

**Issue by weikenxq** [LibreDWG/libredwg#763]
Hello,

I'm trying to convert dwg to dxf using dwg2dxf,  there are some errors and the converted dxf file is invalid.

Are there any way to solve the errors? Is it a bug?

Thank you.

### environment
macOS big sur 11.5.2 , Apple clang version 12.0.5 (clang-1205.0.22.9),GNU Make 3.81, libredwg latest [commit](https://github.com/LibreDWG/libredwg/commit/f0228020f14800a497bb428ef2022c0083aeb8ab)

compile with

./autogen.sh && ./configure --disable-bindings && make && sudo make install

### some information
dwg2dxf -o ~/Downloads/6370a4f740006e9980514aa0ada3187921e2c5c3.dxf  ~/Downloads/6370a4f740006e9980514aa0ada3187921e2c5c3.dwg -y
Reading DWG file /Users/weiken/Downloads/6370a4f740006e9980514aa0ada3187921e2c5c3.dwg
ERROR: Section[13]->pages[0] overflow
ERROR: Invalid System Section
Writing DXF file /Users/weiken/Downloads/6370a4f740006e9980514aa0ada3187921e2c5c3.dxf
ERROR: dwg.block_control and HEADER.BLOCK_CONTROL_OBJECT missing
ERROR: BLOCK_CONTROL missing

origin dwg file open with AutoCAD:
![image](https://github.com/LibreDWG/libredwg/assets/42831401/48fef989-0edc-42b3-bdcc-1b10b131bd23)

### attachment
[6370a4f740006e9980514aa0ada3187921e2c5c3.dwg.zip](https://github.com/LibreDWG/libredwg/files/11744424/6370a4f740006e9980514aa0ada3187921e2c5c3.dwg.zip)

**Comment by rurban** [comment]
This is the first bug:

ERROR: Section[13]->pages[0] overflow

this seems to be new
