### ISSUE TITLE
How to use this? dlls missing

### ISSUE THREAD

**Issue by Aabha-cell** [LibreDWG/libredwg#771]
I downloaded the libredwg-0.12.5.5885-win64.zip and extracted it. I'm trying to run the dwg2svg2.exe. I'm getting a popup saying libredwg-0.dll was not found. How do I get this? Do I need to download anything else?
Please help and guide on how to run the exe files on windows system</div>

**Comment by rurban** [comment]
No, this is the content of  libredwg-0.12.5.5885-win64.zip, and the dll is there.
![image](https://github.com/LibreDWG/libredwg/assets/41809/1948184c-d9cb-499f-86b8-f78547bb6c12)

**Comment by zefreestijl** [comment]
I got the same problem recently,
in Windows System Properties -> Environment Variables, 
edit and add a new Path of the directories where .dll file is located.

**Comment by rurban** [comment]
On windows you just need to keep the dll's in the very same dir as the exe's. Other than that you might need a depends.exe -like tool, which reports which dll's are missing. We cannot help with that.
