### ISSUE TITLE
DWG to JSON and back strings_area issue

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#775]
In https://github.com/LibreDWG/libredwg/issues/346 I described roundtripping issue in conversion between JSON and DWG.

In the conversion from DWG to JSON is used:
```
DWG_TABLE (LTYPE)
...
FIELD_BINARY (strings_area, 256, 0);
```
in dwg.spec
The result of the conversion of "" is 512 character string with zeros.

In the conversion from JSON to DWG is used:
```
in_hex2bin() ...
```
in in_dxf.c
The result of the conversion of 512 character string with zeros is "0".

I am curious when we have in_hex2bin without tests, and there is a copy of this function in unit-testing/add_test.c.

I think that could be fine to have one function and tests with it. + Fix of this issue.

**Comment by michal-josef-spacek** [comment]
btw: I don't know if usage of ```in_hex2bin()``` is fine in this use case.
I was looking to ```FIELD_BINARY``` in in_json(), but this is not used in this case. This is not intuitive too

**Comment by michal-josef-spacek** [comment]
@rurban Could we move this ```in_hex2bin()``` to some common c file? 
I am proposing bits.c :-)

**Comment by rurban** [comment]
Sure. It's used by both importers

**Comment by michal-josef-spacek** [comment]
PR for move: https://github.com/LibreDWG/libredwg/pull/776

**Comment by michal-josef-spacek** [comment]
@rurban Thanks for the tests

**Comment by michal-josef-spacek** [comment]
Hm, this issue is invalid. Error is before this, probably in saving of numdashes.

**Comment by michal-josef-spacek** [comment]
Heh funny bug.

**Comment by michal-josef-spacek** [comment]
PR for fix: https://github.com/LibreDWG/libredwg/pull/778

**Comment by rurban** [comment]
Merged
