### ISSUE TITLE
Issue in dwg_find_color_index()

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#780]
We have an issue in dwg_find_color_index(), which is not working.

The problem is with:
```
BITCODE_BL rgb = 0xff0000;
Dwg_RGB_Palette pal;
pal.r = rgb & 0xff0000;
```
where BITCODE_BL is uint32_t and pal.r is unsigned char and conversion isn't working.

**Comment by michal-josef-spacek** [comment]
Fix is in https://github.com/LibreDWG/libredwg/pull/779

**Comment by michal-josef-spacek** [comment]
@rurban I think, we need tests for this situation. When the function is in dwg.c, to which test file I could add test?

**Comment by rurban** [comment]
I think common_test would fit best

**Comment by michal-josef-spacek** [comment]
PR for tests: https://github.com/LibreDWG/libredwg/pull/782

**Comment by rurban** [comment]
Fixed
