### ISSUE TITLE
2NDHEADER in JSON

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#792]
When I am investigating https://github.com/LibreDWG/libredwg/issues/346 I found that 2NDHEADER isn't in JSON.
When I convert JSON to DWG, the DWG is without 2NDHEADER.

What about adding 2NDHEADER to JSON?
Or do we need to fix the conversion from JSON to DWG by adding 2NDHEADER?

**Comment by rurban** [comment]
We can add this section, yes. For JSON it's redundant, but for roundtrips it would help

**Comment by rurban** [comment]
Now enabled. Maybe we shouldn't write it in release mode.

**Comment by michal-josef-spacek** [comment]
Thanks, I will test it

**Comment by michal-josef-spacek** [comment]
@rurban 
Interesting issue is with conversion to JSON and back
DWG (dwgread -v3)
```
=======> Second Header 3 (start):   163713
...
version: AC1015 [TFF 12]
...
```
Conversions to JSON, output:
```
...
  "SecondHeader": {
    "version": "AC1015\u0000\u0000\u0000\u0000\u0000\u000f",
...
```
Conversion to DWG, dwgread output:
```
=======> Second Header 3 (start):   164204
...
version: AC1015 [TFF 12]
...
```
Conversion to JSON, againg from previous:
```
...
  "SecondHeader": {
    "version": "AC1015",
...
```

When I am looking to sources:
src/in_json.c:
```
FIELD_TFF (version, 12, 0)
```
src/out_json.c:
```
FIELD_TF (version, 12, 0);
```

**Comment by michal-josef-spacek** [comment]
Second issue:
When I convert from DWG to JSON and back.
In Second header in DWG file is:
```
section[i].nr: 0x0 [RC 0]
section[i].address: 0x3723 [BLx 0]
section[i].size: 512 [BL 0]
section[i].nr: 0x1 [RC 0]
section[i].address: 0x3923 [BLx 0]
section[i].size: 1048 [BL 0]
section[i].nr: 0x2 [RC 0]
section[i].address: 0x27cdd [BLx 0]
section[i].size: 1167 [BL 0]
section[i].nr: 0x3 [RC 0]
section[i].address: 0x2816c [BLx 0]
section[i].size: 0 [BL 0]
section[i].nr: 0x0 [RC 0]
^^^^^^^^^^^^^^^^^^^ → We need 0x4
section[i].address: 0x0 [BLx 0]
section[i].size: 0 [BL 0]
section[i].nr: 0x5 [RC 0]
section[i].address: 0x61 [BLx 0]
section[i].size: 123 [BL 0]
```

**Comment by rurban** [comment]
Fixed both

**Comment by michal-josef-spacek** [comment]
The first one is ok. Thanks.

The second one is not ok.
The issue is the bad creating of template record in the second header.

Input JSON file:
[test.json.gz](https://github.com/LibreDWG/libredwg/files/12345288/test.json.gz)

Command to convert: ```dwgwrite test.json```
Output in dwg file is:
```
sections[4].nr: 0 [RCd 0]
sections[4].address: 0 [BL 0]
sections[4].size: 0 [BL 0]
```
We need something like:
```
sections[4].nr: 4 [RCd 0]
sections[4].address: 164349 [BL 0]
sections[4].size: 4 [BL 0]
```

**Comment by rurban** [comment]
Because we write the template after the 2ndheader, and we calc. the dat->byte (address) only then.

so we might need to patch in both section addresses. the first and the 2nd. or calc the template address and size before writing the 2ndheader

**Comment by michal-josef-spacek** [comment]
@rurban Thanks
