### ISSUE TITLE
Issue in 10th handle in second header

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#803]
Test scenario:
Input DWG file (blank file from AutoCAD 2000):
[test.dwg.gz](https://github.com/LibreDWG/libredwg/files/12361564/test.dwg.gz)
When I convert to JSON, 10th handle in JSON:
```
      {
        "nr": 10,
        "hdl": [
          11
        ]
      },
```
Which is backup of ```VX_CONTROL_OBJECT: (3.1.B) abs:11 [H 0]```

After conversion from this JSON to DWG, result will be:
```
handles[10].num_hdl: 1 [RCd 0]
handles[10].nr: 10 [RCd 0]
hdl: { 0x8 } [*RC]
```

As I see, each time will be 0x8 from JSON conversion to DWG. This is bad.

**Comment by michal-josef-spacek** [comment]
I found this issue in investigation of https://github.com/LibreDWG/libredwg/issues/346

**Comment by rurban** [comment]
yes, a typo.
=> SET_HDL (10, VX_CONTROL_OBJECT);

**Comment by michal-josef-spacek** [comment]
Great, it's working. Thank you.
