### ISSUE TITLE
Not enough digits for geojson coordinates

### ISSUE THREAD

**Issue by kemaluzel** [LibreDWG/libredwg#810]
I am saving dwg file as geojson file from command line with dwgread.exe. when I look at the geographic coordinates... it shows 6 digits after the comma. 6 digits is not enough for geographic coordinates. How can I make it to have at least 10 digits.

**Comment by rurban** [comment]
Change that format: https://github.com/LibreDWG/libredwg/blob/eb2fc14b57546964a170b454e202b3669f18440f/src/out_geojson.c#L53

**Comment by kemaluzel** [comment]
I am developing application for gnss. cm precision is important to me, so I need to make the float value at least 8-10 digits.

I cloned version 0.12.5 with git. I compiled them all with visual studio 2022. on the command line...
dwgread.exe "C:\test.DWG" -O GeoJSON -o "C:\test.GEOJSON"
when i run it...

I get the following error. 

Warning: Invalid sections: 0 != numgaps: 0 + numsections: 15
Warning: Unstable Class object 502 MATERIAL (0x481) 63/0
Warning: Unstable Class object 502 MATERIAL (0x481) 64/0
Warning: Unstable Class object 502 MATERIAL (0x481) 65/0
Warning: Unstable Class object 504 TABLESTYLE (0xfff) 101/0
Warning: TODO TABLESTYLE r2010+ missing fields
Warning: Unstable Class object 505 MLEADERSTYLE (0xfff) 103/0
Warning: Unstable Class object 506 SUN (0x481) 104/0
SUCCESS

What could be the problem? can you help?

**Comment by rurban** [comment]
No errors, just warnings. And irrelevant to geojson export

**Comment by kemaluzel** [comment]
Tried LibreDWG-master and version v0.12.5, dwgread not working after compiling. It doesn't output the geojson file.

**Comment by kemaluzel** [comment]
Added jsmn files to libredwg-0.12.5.6183/jsmn folder and compiled in visual studio 2022. compilation completed successfully. 

on the command line...

dwgread.exe "C:\Users\kemal\OneDrive\Desktop\datalar\BOLGE_HHAZIR_GEO.DWG" -O GeoJSON -o "C:\Users\kemal\OneDrive\Desktop\datalar\test.GEOJSON"

it is not saving geojson file in this directory.

**Comment by rurban** [comment]
sorry, with open source you should be able apply one of the 6 different build recipes on windows by yourself:
github: mingw, mingw-cmake, vs-cmake, vs-ninja
appveyor: 32bit and 64bit

**Comment by rurban** [comment]
I've decided to overrule the GeoJSON RFC and add a configure option --with-geomjson-precision=default
to emit the default 6 digits, and as default or with --with-geomjson-precision=max emit the max digits.
similar with DXF output precision: --with-dxf-precision=default or --with-dxf-precision=max.

a seperate run-time dwgread arg would be overkill, also a seperate dwggeojson program.
for dwg2dxf though a seperate arg would make sense, to override the config setting.

**Comment by kemaluzel** [comment]
Perfect, I'm so happy.

https://github.com/LibreDWG/libredwg/releases/tag/0.12.5.6220

I downloaded "libredwg-0.12.5.6220-win64.zip" from the link.

On the command line:
dwgread.exe "C:\test.DWG" -O GeoJSON -o "C:\test.GEOJSON" --with-geojson-precision=max
I get an error when I run it. I am sending the wrong command. Can you write an example command?

**Comment by kemaluzel** [comment]
Unfortunately I couldn't and I couldn't understand what to do. Could you please be more descriptive.

**Comment by kemaluzel** [comment]
where do i run this code?
add config --with-geojson-precision=max
After running this I need to compile the code.
