### ISSUE TITLE
JSON file sizes

### ISSUE THREAD

**Issue by turtle0x1** [LibreDWG/libredwg#837]
For me a 1.5MB DWG gets expanded to about 21MB of JSON, which is about a 1300% increase in storage requirements!

Luckily I can trash the JSON when I'm done but the storage requirements is quite the increase.

A wild guess would be the JSON keys being repeated "long_strings" does the most damage.

Is the filesize a concern for this project? I'm guessing probably not

**Comment by turtle0x1** [comment]
I agree as general point / project direction - its not your problem.

But as an administrator if I dont delete my DWG's < 2TB turns to > 22TB - which simply I cant tolerate.

Adding golang bindings as a TODO on this repo.

**Comment by michal-josef-spacek** [comment]
@turtle0x1 
> For me a 1.5MB DWG gets expanded to about 21MB of JSON, which is about a 1300% increase in storage requirements!

btw: I don't think that's an argument. JSON is a text format, when you are trying to resolve storage, you could compress.
