### ISSUE TITLE
Make seems capped at 4 CPU processes?

### ISSUE THREAD

**Issue by turtle0x1** [LibreDWG/libredwg#838]
Pretty self explanatory, no matter what I pass I.E `-j12` - it has no impact

**Comment by turtle0x1** [comment]
Changed the following line to `-j12` - then set via `make -j12` when building - dunno if it being dumb or what? close if required.

https://github.com/LibreDWG/libredwg/blob/524364b216354e5a4297861456f3811f3e697ead/Makefile.am#L264

**Comment by rurban** [comment]
Can be replaced with $(NPROC), but it might be tricky for portability

**Comment by turtle0x1** [comment]
Can we use [GNU Conditional Syntax](https://www.gnu.org/software/make/manual/html_node/Conditional-Syntax.html) to say if argument passed otherwise default to 4?

**Comment by rurban** [comment]
cppcheck is not that important to risk compat breakage
