### ISSUE TITLE
 LOG_ERROR ("Invalid Data Section Page Map type 0x%x != 0x4163003b",                      FIELD_VALUE (section_type));

### ISSUE THREAD

**Issue by qwuip789** [LibreDWG/libredwg#846]
There is an error decoding DWG in 2004 format. What is the cause of this error?

**Comment by rurban** [comment]
The cause is that there is a Invalid Data Section Page Map type, as written

**Comment by rurban** [comment]
without example dwg there no way to go further. but most likely the known section page map bug, #439, #144, ...
