### ISSUE TITLE
Add support for encoding of ObjFreeSpace from JSON to DWG (AC1012)

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#872]
This is not working in AC1012.
Example:
[first.json.gz](https://github.com/LibreDWG/libredwg/files/13458457/first.json.gz)
Output is:
```
section[3].number:         0 [RC] AcDb:ObjFreeSpace
section[3].address:        0 [RL]
section[3].size:           0 [RL]
```

Missing number of section.
Missing section from JSON.

**Comment by rurban** [comment]
I had it since r13c3, according to the spec. Changed to r13 now.

**Comment by michal-josef-spacek** [comment]
The situation is, that could be AC1012 JSON file with ObjFreeSpace or without.
When is present, we need to encode. When is not present, not encode.

**Comment by michal-josef-spacek** [comment]
Seems ok, thanks.
