### ISSUE TITLE
How to read the Dwg_Entity_LINE:  layer and ltype?

### ISSUE THREAD

**Issue by iisaxin** [LibreDWG/libredwg#903]
Hello everyone, thanks for the author's contribution, let me have the opportunity to use libredwg in my work, now I encounter a problem, such as I read the Dwg_Entity_LINE, insert points I can easily get, but for example, how to obtain the "layer" and "ltype" but no idea, do you have any relevant routines? thanks

 for (i = 0; i < dwg.num_objects; i++)
    {
		switch (dwg.object[i].fixedtype)
		{
                       case DWG_TYPE_LINE:
                       {line = dwg.object[i].tio.entity->tio.LINE;
			color=dwg.object[i].tio.entity->color;
                       //layer=??
                        //ltype=??

**Comment by rurban** [comment]
Please move that to Discussions. Not an issue
