### ISSUE TITLE
accidental line? ACDBASSOCOSNAPPOINTREFACTIONPARAM

### ISSUE THREAD

**Issue by fr-an-k** [LibreDWG/libredwg#905]
This subclass in dwg.spec (currently line 11930) seems to be the only one referenced by all capitals instead of camelcase:
ACDBASSOCOSNAPPOINTREFACTIONPARAM
Judging by the pattern in other DWG_OBJECT declarations, it doesn't seem right, but I could be wrong.

**Comment by rurban** [comment]
No camel-case because autodesk.
It's a valid class AND a valid subclass.
