### ISSUE TITLE
Where to find ODA-5.4.1.md?

### ISSUE THREAD

**Issue by fr-an-k** [LibreDWG/libredwg#909]
Where did you find the original md file?
I'm trying to apply the patch to the pdf but it's not documented and nothing I try works:

```
patch < ODA-5.4.2-libredwg-diff.pdf OpenDesign_Specification_for_.dwg_files.pdf
patch: **** Only garbage was found in the patch input.

git apply < ODA-5.4.2-libredwg.patch
error: doc/ODA-5.4.2-libredwg.md: No such file or directory
```

**Comment by rurban** [comment]
I created it privately for copyright reasons. The patch is only for informational reasons, that's why you should look at doc/ODA-5.4.2-libredwg-diff.pdf
But a patch to the original pdf would also a good idea, thanks.
