### ISSUE TITLE
Memory leak in function 'bit_TV_to_utf8'

### ISSUE THREAD

**Issue by JoraGevorgyan** [LibreDWG/libredwg#926]
The memory leak is found by a static analyzer developed at [CAST]( https://www.linkedin.com/company/cast-center/).

The memory allocated [at line 3290](https://github.com/LibreDWG/libredwg/blob/057653b37a7bb45cdfa8cecddfaad95b8c20c441/src/bits.c#L3290) may left without free in case of returning from [line 3366](https://github.com/LibreDWG/libredwg/blob/057653b37a7bb45cdfa8cecddfaad95b8c20c441/src/bits.c#L3366).

**Comment by rurban** [comment]
Oh, yeah. I see it now

**Comment by rurban** [comment]
ossfuzz believes this is fixed now
