### ISSUE TITLE
Improve releasing (see release 0.13.2)

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#939]
I saved release 0.13.2 from github release page (https://github.com/LibreDWG/libredwg/archive/refs/tags/0.13.2.tar.gz)
Issues:
1) There is no configure script in tarball.
2) When I run autogen.sh, there are many warning about not present git repository.

**Comment by michal-josef-spacek** [comment]
Another thing:
```
  CC       in_json.lo
in_json.c:55:10: fatal error: ../jsmn/jsmn.h: Adresář nebo soubor neexistuje
   55 | #include "../jsmn/jsmn.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by rurban** [comment]
1. Fatal. But I tested it by myself, interesting.
2. Needs to be silenced somehow
3. Uh, forgot jsmn

**Comment by rurban** [comment]
Unfortunately a wont-fix: https://github.com/orgs/community/discussions/6003
