### ISSUE TITLE
how to build libredwg with visual studio 2019

### ISSUE THREAD

**Issue by hjxy2012** [LibreDWG/libredwg#942]
I got “We do support mingw, clang-cl and now also Visual Studio 2019 via cmake. stdint.h and inttypes.h must be available.” from the readme file. So how to build libredwg with visual studio 2019. Thank you.

**Comment by rurban** [comment]
See the github actions recipe

Zongyao Li ***@***.***> schrieb am Fr., 23. Feb. 2024, 17:31:
