### ISSUE TITLE
Simplified Chinese decoding

### ISSUE THREAD

**Issue by xiuweihan** [LibreDWG/libredwg#945]
Use dwglayers.exe:
[libredwg-0.13.3-win64.zip](https://github.com/LibreDWG/libredwg/files/14445953/libredwg-0.13.3-win64.zip)
 to output the layer names of the dwg file. Some layers contain Chinese characters and garbled characters are output.

file：
[read_layer_name.zip](https://github.com/LibreDWG/libredwg/files/14445924/read_layer_name.zip)

result:
0
鍖哄煙-green area
PV ARRAY LIMIT
site
鍖哄煙 E-SUBSTATION
E-INVERTER_STATION
鍖哄煙-閬撹矾
*ADSK_SYSTEM_LIGHTS
DGX
GstarFastview4.2-ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-note-layer-HCNoteLayer
ZAW

**Comment by rurban** [comment]
The names do look good to me. Are they wrong?

**Comment by rurban** [comment]
I'm having trouble with my hard disc, with constant corruptions. Will need some time

**Comment by rurban** [comment]
oda converts them to these layers:

0
区域-green area
PV ARRAY LIMIT
site
区域 E-SUBSTATION
E-INVERTER_STATION
区域-道路
*ADSK_SYSTEM_LIGHTS
DGX
GstarFastview4.2-ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-note-layer-HCNoteLayer
ZAW

They still do look very chinese to me

**Comment by zefreestijl** [comment]
Hi, I've encountered the same problem recently,
as rurban says, the program or the library itself is correct,
the problem is from codepage, 

add line of : system("chcp 65001") 
at the begins of mian() works for me.

**Comment by rurban** [comment]
The library was not quite correct, just found a major decoding problem: #959 
But this should not affect you in this case.
