### ISSUE TITLE
GeoJSON colors how?

### ISSUE THREAD

**Issue by awefire** [LibreDWG/libredwg#95]
I convert dwg to GeoJSON using binary 0.7.1600 dwgread.exe.But the output GeoJSON is empty.
![image](https://user-images.githubusercontent.com/37166494/52757375-652c8480-303f-11e9-9aa1-7f6d7e9a5764.png)

**Comment by rurban** [comment]
The currently covered entity types with GeoJSON are:
INSERT, POLYLINE_2D, POLYLINE_3D, LINE, POINT, 
LWPOLYLINE, GEOPOSITIONMARKER

If it's empty your dwg has none of such entities.

**Comment by Febfire** [comment]
POLYLINE_3D and MTEXT inside.
[redwg1.zip](https://github.com/LibreDWG/libredwg/files/2874185/redwg1.zip)

**Comment by Febfire** [comment]
hi rurban.
I realized that the MTEXT that is not supported causes the parsing to fail.
I look forward to knowing how long I can support the TEXT and MTEXT?

**Comment by Febfire** [comment]
It seems that read POLYLINE_3D failed.Just LINE feature inside in output GeoJSON.

**Comment by rurban** [comment]
There's no POLYLINE_3D in your example, just a LWPOLYLINE.
I've added now support for the Text in feature for TEXT, MTEXT, INSERT

**Comment by Febfire** [comment]
can i extract the color of entity while convrting GeoJSON?

**Comment by rurban** [comment]
Not yet. I need to see an example how this fearure is represented. Color as index or rgb?

**Comment by Febfire** [comment]
Rgb or hex in need,just like the GeoJSON from dxf using GDAL.But it doesn't support dwg.

**Comment by rurban** [comment]
can you point me to an example, how the rgb is encoded.
Now I added color as number for the index, Google maps accepts color names as string.
eg. 
```
"properties": {
        "SubClasses": "AcDbEntity:AcDbLine",
        "Layer": "Tavolo 3",
        "color": 256,
        "EntityHandle": "8B",
        "Text": null
      },
```

**Comment by Febfire** [comment]
I used secondary development techniques of AutoCAD to extract color rgb and convert it to hexadecimal.
eg.
(255,255,0) => (#ffff00)
Maybe color index isn't a good choice.I think that the hex is pretty well.

**Comment by rurban** [comment]
There many possibilities how colors can be encoded in GeoJSON. We need to pick one.

1. map color with index: int, name: str, rgb: str, alpha: int
eg
```
"color":  {
        "index": 1,
        "rgb": "000007"
      }
```

2. dynamic types to seperate name, rgb or index.
eg `"color": 0, "color": "blue", color: "00ff00"`

3. seperate keys for each type.
eg `"color_index": 0, "color_name": "blue", color_rgb: "00ff00"`

mostly I have no idea of exiting GeoJSON readers, how they accept a color property.

**Comment by Febfire** [comment]
I think the second one is a good choice, as of the GeoJSON I have seen.

**Comment by rurban** [comment]
I added now variant, but without the names. 
So far I found examples for names pointing to a DBCOLOR handle with something like "DIC 381". 
I believe rgb hex is better for this (rgb": "6CA573")

**Comment by rurban** [comment]
I've changed now the hex format to have a leading '#', like '#000000'
