### ISSUE TITLE
 I only want the dwg2dxf function, how can I compile it on Linux?

### ISSUE THREAD

**Issue by tigerdhl** [LibreDWG/libredwg#950]
Hi,  I only want the dwg2dxf function, how can I compile it on Linux?

**Comment by rurban** [comment]
Not a bug, please use Discussions for such questions.

read the README.

```
sh ./autogen.sh # if you checked out the source code from git
./configure --disable-bindings --disable-shared
make -C src
make -C programs dwg2dxf
```

**Comment by tigerdhl** [comment]
> Not a bug, please use Discussions for such questions.
> 
> read the README.
> 
> ```
> sh ./autogen.sh # if you checked out the source code from git
> ./configure --disable-bindings --disable-shared
> make -C src
> make -C programs dwg2dxf
> ```

Thank u!
