### ISSUE TITLE
Fix MATERIAL class

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#954]
When I compile libredwg without ```--enable-debug``` (tested on mingw cross compilation). The conversion of DWG with MATERIAL class to JSON and back is not working. Output DWG file is not possible to open in AutoCAD.

This is partially related to the implementation of MATERIAL class.

**Comment by rurban** [comment]
MATERIAL.gentexture and several other MATERIAL features are not yet supported. These should be disabled without DEBUG

**Comment by michal-josef-spacek** [comment]
If I understand correctly, we need to stable MATERIAL class and after this, we could remove hacks for roundtripping for MATERIAL (https://github.com/LibreDWG/libredwg/blob/master/src/encode.c#L3277). Am I right?

**Comment by rurban** [comment]
We won't get procedural Materials stable anytime soon, but the rest would be great. So encode should warn and disable it. Just enable it with enable-debug

**Comment by rurban** [comment]
renaming IMAGE,WIPEOUT.size to image_size fixed the debug json roundtrip

**Comment by rurban** [comment]
I've re-enabled MATERIAL (and WIPEOUT) in the branch smoke/material. No oda errors with r2000 json roundtrips anymore. But still oda errors with r2004-2018

**Comment by michal-josef-spacek** [comment]
This is working for me.
