### ISSUE TITLE
can i get layer switch state

### ISSUE THREAD

**Issue by guguTang** [LibreDWG/libredwg#96]
layer->on always is 0

**Comment by rurban** [comment]
layer->on is not reliably set r13+, because the off state is of the color index is negative.
maybe we should set this value.

**Comment by rurban** [comment]
I found another bug in LAYER.on: with r2000 the flag was reverse. Fixed now all instances with 1ee166e3a9608a1f034dd18b5c47e86a2ebf1ee9

**Comment by rurban** [comment]
You can try 0.7.1619 and later

**Comment by guguTang** [comment]
i use 0.7.1621 and it's work. Thanks!
