### ISSUE TITLE
Issue with HANDLE > 32b

### ISSUE THREAD

**Issue by michal-josef-spacek** [LibreDWG/libredwg#967]
Example:
[foo.dwg.gz](https://github.com/LibreDWG/libredwg/files/14706236/foo.dwg.gz)

Actually:
```
handle: 0.3.FFFF [H 5]
```

Expected:
```
handle: 0.3.19FFFF [H 5]
```

Because (src/bits.c):
```
   if (dat->version < R_2018) // FIXME where did I see 64bit handles?
     handle->value &= 0xFFFF
```

**Comment by rurban** [comment]
Yes, it should be capped at 64bit, not 32. Thanks
