### ISSUE TITLE
The necessary files are missing when installing

### ISSUE THREAD

**Issue by oyoyogg** [LibreDWG/libredwg#978]
Hello, I need to use files like out_json.h and hash.h when installing and compiling, but the current installation method does not include these related files. Do you have a good solution for this? Thank you

**Comment by rurban** [comment]
Where are out_json.h or hash.h needed? These are purely internal headers, and don't need to be installed.

They should be in the tar ball or git repos

**Comment by oyoyogg** [comment]
After installing, I want to use methods similar to those in out_json.h in my own development tool(to convert some object of dwg to JSON), but the installation directory only has dwg.h or dwg_api.h, does that mean I need to implement those methods in my own code?Thank you

**Comment by oyoyogg** [comment]
> Where are out_json.h or hash.h needed? These are purely internal headers, and don't need to be installed.
> 
> They should be in the tar ball or git repos
https://github.com/LibreDWG/libredwg/issues/978#issuecomment-2135520678


> Where are out_json.h or hash.h needed? These are purely internal headers, and don't need to be installed.
> 
> They should be in the tar ball or git repos

After installing, I want to use methods similar to those in out_json.h in my own development tool(to convert some object of dwg to JSON), but the installation directory only has dwg.h or dwg_api.h, does that mean I need to implement those methods in my own code?Thank you

**Comment by rurban** [comment]
Then you need to use the source dist, not the package.
